"""Pack source — pack_10_documents"""

ENTITIES = [
    {
        'id': 'cap.doc.ingest',
        'type': 'capability',
        'name': 'Ingest Document',
        'description': 'Ingest a document artifact into the pipeline, validate format, and register provenance.',
        'risk_tier': 'medium',
        'tags': [
            'docs',
            'ingest',
            'pipeline',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 1,
            'financial': 0,
            'time': 1,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
            'ctrl.obs.run-metadata-store',
        ],
        'idempotency': 'partial',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.doc.ocr',
        'type': 'capability',
        'name': 'OCR Document',
        'description': 'Extract text and layout from a document using optical character recognition.',
        'risk_tier': 'medium',
        'tags': [
            'docs',
            'ocr',
            'ml',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 0,
            'financial': 1,
            'time': 2,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
            'ctrl.obs.metrics-core',
        ],
        'idempotency': 'partial',
        'determinism': 'non-deterministic',
    },
    {
        'id': 'cap.doc.classify',
        'type': 'capability',
        'name': 'Classify Document',
        'description': 'Classify a document by type, sensitivity, and routing category.',
        'risk_tier': 'medium',
        'tags': [
            'docs',
            'classification',
            'ml',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 0,
            'financial': 0,
            'time': 1,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
        ],
        'idempotency': 'full',
        'determinism': 'captured',
    },
    {
        'id': 'cap.doc.redact',
        'type': 'capability',
        'name': 'Redact Document',
        'description': 'Apply PII/PHI/PCI redactions to a document using rule or ML-based detection.',
        'risk_tier': 'high',
        'tags': [
            'docs',
            'redaction',
            'privacy',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 3,
            'network': 0,
            'financial': 1,
            'time': 2,
            'reversibility': 'irreversible',
        },
        'typical_controls': [
            'ctrl.obs.audit-log-append-only',
            'ctrl.sandbox.workspace-mounts-only',
        ],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.doc.stamp',
        'type': 'capability',
        'name': 'Stamp Document',
        'description': 'Apply a visible or invisible processing stamp (watermark, classification label) to a document.',
        'risk_tier': 'medium',
        'tags': [
            'docs',
            'stamping',
            'provenance',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 0,
            'financial': 0,
            'time': 1,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
        ],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.doc.sign',
        'type': 'capability',
        'name': 'Sign Document',
        'description': 'Apply a cryptographic digital signature to a document artifact using an isolated key.',
        'risk_tier': 'critical',
        'tags': [
            'docs',
            'signing',
            'security',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 2,
            'network': 0,
            'financial': 2,
            'time': 1,
            'reversibility': 'irreversible',
        },
        'typical_controls': [
            'ctrl.obs.audit-log-append-only',
            'ctrl.sandbox.secrets-denied-by-default',
        ],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.doc.hash-artifact',
        'type': 'capability',
        'name': 'Hash Document Artifact',
        'description': 'Compute and record the cryptographic hash of a document artifact for integrity verification.',
        'risk_tier': 'medium',
        'tags': [
            'docs',
            'hashing',
            'integrity',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 0,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.obs.run-metadata-store',
        ],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'wrk.doc.pipeline.orchestrator',
        'type': 'worker_species',
        'name': 'Document Pipeline Orchestrator',
        'description': 'Orchestrate multi-step document pipeline with resumability and audit.',
        'risk_tier': 'high',
        'determinism': 'captured-deterministic',
        'required_controls': [
            'ctrl.obs.structured-logging',
            'ctrl.obs.audit-log-append-only',
            'ctrl.sandbox.flight-recorder',
        ],
        'tags': [
            'docs',
            'orchestration',
        ],
        'serves_capabilities': [
            'cap.doc.ingest',
            'cap.doc.ocr',
            'cap.doc.classify',
            'cap.doc.stamp',
        ],
        'blast_radius_hint': {
            'data': 3,
            'network': 1,
            'financial': 1,
            'time': 3,
            'reversibility': 'partially-reversible',
        },
        'idempotency': 'partial',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'wrk.doc.ocr.worker',
        'type': 'worker_species',
        'name': 'OCR Worker',
        'description': 'Run OCR and return text and layout with confidence metrics.',
        'risk_tier': 'medium',
        'determinism': 'nondeterministic',
        'required_controls': [
            'ctrl.obs.structured-logging',
            'ctrl.obs.metrics-core',
        ],
        'tags': [
            'docs',
            'ocr',
            'ml',
        ],
        'serves_capabilities': [
            'cap.doc.ocr',
        ],
        'blast_radius_hint': {
            'data': 1,
            'network': 0,
            'financial': 1,
            'time': 2,
            'reversibility': 'reversible',
        },
        'idempotency': 'partial',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'wrk.doc.redaction.worker',
        'type': 'worker_species',
        'name': 'Document Redaction Worker',
        'description': 'Apply redactions using templates/rules; emit redaction report.',
        'risk_tier': 'high',
        'determinism': 'deterministic',
        'required_controls': [
            'ctrl.obs.audit-log-append-only',
            'ctrl.sandbox.workspace-mounts-only',
        ],
        'tags': [
            'docs',
            'redaction',
        ],
        'serves_capabilities': [
            'cap.doc.redact',
        ],
        'blast_radius_hint': {
            'data': 3,
            'network': 0,
            'financial': 1,
            'time': 2,
            'reversibility': 'irreversible',
        },
        'idempotency': 'full',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'wrk.doc.signing.worker',
        'type': 'worker_species',
        'name': 'Document Signing Worker',
        'description': 'Apply digital signatures using isolated keys; verify signatures.',
        'risk_tier': 'critical',
        'determinism': 'deterministic',
        'required_controls': [
            'ctrl.obs.audit-log-append-only',
            'ctrl.sandbox.secrets-denied-by-default',
        ],
        'tags': [
            'docs',
            'signing',
            'security',
        ],
        'serves_capabilities': [
            'cap.doc.sign',
            'cap.doc.hash-artifact',
        ],
        'blast_radius_hint': {
            'data': 2,
            'network': 0,
            'financial': 2,
            'time': 1,
            'reversibility': 'irreversible',
        },
        'idempotency': 'full',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.doc.untrusted-sandboxed',
        'type': 'profile',
        'name': 'Untrusted Sandboxed Document Profile',
        'description': 'Process untrusted/external documents in strict sandboxed environment.',
        'tags': [
            'docs',
            'sandbox',
            'security',
        ],
        'controls_required': [
            'ctrl.sandbox.no-egress-default-deny',
            'ctrl.sandbox.workspace-mounts-only',
            'ctrl.sandbox.resource-limits-strict',
            'ctrl.obs.structured-logging',
        ],
        'recommended_for_risk_tiers': [
            'medium',
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.doc.signed-highrisk',
        'type': 'profile',
        'name': 'High-Risk Signed Document Profile',
        'description': 'Process high-risk documents with mandatory signing, audit, and isolation.',
        'tags': [
            'docs',
            'signing',
            'security',
        ],
        'controls_required': [
            'ctrl.obs.audit-log-append-only',
            'ctrl.sandbox.secrets-denied-by-default',
            'ctrl.obs.flight-recorder-bundle',
        ],
        'recommended_for_risk_tiers': [
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.doc.restricted-redaction',
        'type': 'profile',
        'name': 'Restricted Redaction Document Profile',
        'description': 'Process documents with restricted data requiring redaction before sharing.',
        'tags': [
            'docs',
            'redaction',
            'compliance',
        ],
        'controls_required': [
            'ctrl.obs.audit-log-append-only',
            'ctrl.sandbox.workspace-mounts-only',
            'ctrl.obs.structured-logging',
        ],
        'recommended_for_risk_tiers': [
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
]
