"""Pack 12: Security Scanning / Supply Chain"""

PACKS = [
    {
        "id": "pack.12",
        "name": "Security Scanning / Supply Chain",
        "entity_count": 10,
    },
]

ENTITIES = [
    # --- Capabilities ---
    {
        "id": "cap.scan.sast",
        "type": "capability",
        "pack_id": "pack.12",
        "name": "SAST Scan",
        "description": "Run static application security testing scan on source code or compiled artifacts.",
        "risk_tier": "medium",
        "tags": ["security", "sast", "scanning"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 2, "reversibility": "reversible"},
        "typical_controls": ["ctrl.sandbox.no_egress_default_deny", "ctrl.obs.structured_logging"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.scan.deps",
        "type": "capability",
        "pack_id": "pack.12",
        "name": "Dependency Scan",
        "description": "Scan project dependencies for known CVEs and risky licenses.",
        "risk_tier": "medium",
        "tags": ["security", "supply-chain", "dependencies"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 1, "financial": 0, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.scan.sbom.generate",
        "type": "capability",
        "pack_id": "pack.12",
        "name": "Generate SBOM",
        "description": "Generate a Software Bill of Materials (SBOM) in SPDX or CycloneDX format.",
        "risk_tier": "low",
        "tags": ["security", "sbom", "supply-chain"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.run_metadata_store"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.scan.dast",
        "type": "capability",
        "pack_id": "pack.12",
        "name": "DAST Scan",
        "description": "Run dynamic application security testing against a live endpoint.",
        "risk_tier": "high",
        "tags": ["security", "dast", "scanning"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 3, "financial": 1, "time": 3, "reversibility": "partially-reversible"},
        "typical_controls": ["ctrl.obs.structured_logging", "ctrl.obs.audit_log_append_only"],
        "idempotency": "partial",
        "determinism": "non-deterministic",
    },
    {
        "id": "cap.verify.artifact_integrity",
        "type": "capability",
        "pack_id": "pack.12",
        "name": "Verify Artifact Integrity",
        "description": "Verify cryptographic digest and/or signature of a build artifact before execution.",
        "risk_tier": "high",
        "tags": ["security", "signing", "supply-chain"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    # --- Worker Species ---
    {
        "id": "wrk.sec.sast.scanner",
        "type": "worker_species",
        "pack_id": "pack.12",
        "name": "SAST Scanner Worker",
        "description": "Run static code scans; normalize findings; gate build.",
        "risk_tier": "medium",
        "level": "L4",
        "guarantee": "best-effort",
        "determinism": "deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.structured_logging",
            "ctrl.sandbox.no_egress_default_deny",
        ],
        "handles_capabilities": ["cap.scan.sast"],
        "tags": ["security", "sast", "supply-chain"],
        "serves_capabilities": ["cap.scan.sast"],
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 2, "reversibility": "reversible"},
        "idempotency": "full",
    },
    {
        "id": "wrk.sec.deps.scanner",
        "type": "worker_species",
        "pack_id": "pack.12",
        "name": "Dependency Scanner Worker",
        "description": "Scan dependencies for CVEs and risky licenses; generate SBOM.",
        "risk_tier": "medium",
        "level": "L4",
        "guarantee": "best-effort",
        "determinism": "deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.structured_logging",
        ],
        "handles_capabilities": [
            "cap.scan.deps",
            "cap.scan.sbom.generate",
        ],
        "tags": ["security", "supply-chain", "sbom"],
        "serves_capabilities": ["cap.scan.deps", "cap.scan.sbom.generate"],
        "blast_radius_hint": {"data": 0, "network": 1, "financial": 0, "time": 1, "reversibility": "reversible"},
        "idempotency": "full",
    },
    {
        "id": "wrk.sec.artifact.verifier",
        "type": "worker_species",
        "pack_id": "pack.12",
        "name": "Artifact Verifier Worker",
        "description": "Verify artifact digests/signatures before execution.",
        "risk_tier": "high",
        "level": "L5",
        "guarantee": "at-least-once",
        "determinism": "deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.audit_log_append_only",
        ],
        "handles_capabilities": ["cap.verify.artifact_integrity"],
        "tags": ["security", "supply-chain", "signing"],
        "serves_capabilities": ["cap.verify.artifact_integrity"],
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "idempotency": "full",
    },
    # --- Profiles ---
    {
        "id": "prof.sec.ci_gated",
        "type": "profile",
        "pack_id": "pack.12",
        "name": "CI-Gated Security Profile",
        "description": "CI pipeline security posture: SAST, dependency scan, and SBOM on every build.",
        "tags": ["security", "ci", "supply-chain"],
        "controls_required": [
            "ctrl.obs.structured_logging",
            "ctrl.sandbox.no_egress_default_deny",
        ],
        "recommended_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "prof.sec.artifact_strict",
        "type": "profile",
        "pack_id": "pack.12",
        "name": "Strict Artifact Security Profile",
        "description": "Strict artifact security posture: mandatory signature verification and full audit trail before execution.",
        "tags": ["security", "signing", "supply-chain"],
        "controls_required": [
            "ctrl.obs.audit_log_append_only",
            "ctrl.obs.structured_logging",
        ],
        "recommended_for_risk_tiers": ["high", "critical"],
    },
]
