"""Pack 19: Model Ops (Eval, Drift, Prompt/Tool QA)"""

PACKS = [
    {
        "id": "pack.19",
        "name": "Model Ops (Eval, Drift, Prompt/Tool QA)",
        "entity_count": 10,
    },
]

ENTITIES = [
    # --- Capabilities ---
    {
        "id": "cap.model.eval.run",
        "type": "capability",
        "pack_id": "pack.19",
        "name": "Run Model Eval",
        "description": "Execute an evaluation suite against a model, prompt, or tool version and publish scores.",
        "risk_tier": "medium",
        "tags": ["mlops", "eval", "quality"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 1, "financial": 2, "time": 3, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.metrics_core", "ctrl.obs.structured_logging"],
        "idempotency": "partial",
        "determinism": "non-deterministic",
    },
    {
        "id": "cap.model.prompts.update",
        "type": "capability",
        "pack_id": "pack.19",
        "name": "Update Prompt Templates",
        "description": "Update versioned prompt templates after safety eval and approval gate.",
        "risk_tier": "high",
        "tags": ["mlops", "prompts", "change-control"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 2, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only", "ctrl.pol.policy_versioning"],
        "idempotency": "partial",
        "determinism": "deterministic",
    },
    {
        "id": "cap.model.tools.update",
        "type": "capability",
        "pack_id": "pack.19",
        "name": "Update Tool Definitions",
        "description": "Update versioned tool definitions (function specs, schemas) after QA gate.",
        "risk_tier": "high",
        "tags": ["mlops", "tools", "change-control"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 2, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only", "ctrl.pol.policy_versioning"],
        "idempotency": "partial",
        "determinism": "deterministic",
    },
    {
        "id": "cap.model.drift.detect",
        "type": "capability",
        "pack_id": "pack.19",
        "name": "Detect Model Drift",
        "description": "Detect statistical drift in model output quality, safety, or cost over time.",
        "risk_tier": "medium",
        "tags": ["mlops", "drift", "observability"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.metrics_core", "ctrl.obs.slo_alerting"],
        "idempotency": "full",
        "determinism": "non-deterministic",
    },
    {
        "id": "cap.model.prompt_injection_test",
        "type": "capability",
        "pack_id": "pack.19",
        "name": "Prompt Injection Test",
        "description": "Run prompt injection attack vectors against a model to validate safety guardrails.",
        "risk_tier": "medium",
        "tags": ["mlops", "safety", "security"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 1, "financial": 1, "time": 2, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging", "ctrl.sandbox.no_egress_default_deny"],
        "idempotency": "partial",
        "determinism": "non-deterministic",
    },
    # --- Worker Species ---
    {
        "id": "wrk.model.eval.runner",
        "type": "worker_species",
        "pack_id": "pack.19",
        "name": "Model Eval Runner Worker",
        "description": "Run eval suites against model/prompt/tool versions; publish scores.",
        "risk_tier": "medium",
        "level": "L4",
        "guarantee": "best-effort",
        "determinism": "nondeterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.metrics_core",
            "ctrl.obs.structured_logging",
        ],
        "handles_capabilities": [
            "cap.model.eval.run",
            "cap.model.prompt_injection_test",
        ],
        "tags": ["mlops", "eval"],
        "serves_capabilities": ["cap.model.eval.run", "cap.model.prompt_injection_test"],
        "blast_radius_hint": {"data": 0, "network": 1, "financial": 2, "time": 3, "reversibility": "reversible"},
        "idempotency": "partial",
    },
    {
        "id": "wrk.model.drift.monitor",
        "type": "worker_species",
        "pack_id": "pack.19",
        "name": "Model Drift Monitor Worker",
        "description": "Monitor production for drift in quality/safety/cost; trigger alerts.",
        "risk_tier": "medium",
        "level": "L4",
        "guarantee": "best-effort",
        "determinism": "nondeterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.metrics_core",
            "ctrl.obs.slo_alerting",
        ],
        "handles_capabilities": ["cap.model.drift.detect"],
        "tags": ["mlops", "drift", "observability"],
        "serves_capabilities": ["cap.model.drift.detect"],
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "idempotency": "full",
    },
    {
        "id": "wrk.model.prompt_qa.gate",
        "type": "worker_species",
        "pack_id": "pack.19",
        "name": "Prompt QA Gate Worker",
        "description": "Gate prompt/tool changes via safety evals, approvals, and canary rollout.",
        "risk_tier": "high",
        "level": "L5",
        "guarantee": "exactly-once",
        "determinism": "deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.audit_log_append_only",
        ],
        "handles_capabilities": [
            "cap.model.prompts.update",
            "cap.model.tools.update",
        ],
        "tags": ["mlops", "prompts", "safety"],
        "serves_capabilities": ["cap.model.prompts.update", "cap.model.tools.update"],
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 2, "time": 1, "reversibility": "reversible"},
        "idempotency": "partial",
    },
    # --- Profiles ---
    {
        "id": "prof.model.release_gated",
        "type": "profile",
        "pack_id": "pack.19",
        "name": "Release-Gated Model Profile",
        "description": "Release gate posture: mandatory eval, safety tests, and approval before model/prompt/tool promotion.",
        "tags": ["mlops", "release", "safety"],
        "controls_required": [
            "ctrl.obs.audit_log_append_only",
            "ctrl.obs.metrics_core",
            "ctrl.pol.policy_versioning",
        ],
        "recommended_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "prof.model.drift_strict",
        "type": "profile",
        "pack_id": "pack.19",
        "name": "Strict Drift Monitoring Model Profile",
        "description": "Strict drift monitoring posture: continuous SLO-based alerting and automated remediation triggers.",
        "tags": ["mlops", "drift", "observability"],
        "controls_required": [
            "ctrl.obs.metrics_core",
            "ctrl.obs.slo_alerting",
            "ctrl.obs.structured_logging",
        ],
        "recommended_for_risk_tiers": ["medium", "high", "critical"],
    },
]
