"""Pack source — pack_22_data_plane"""

PACKS = [
    {
        'id': 'pack.22',
        'name': 'Data Plane (DB Patterns, Migrations, Consistency)',
        'entity_count': 9,
    },
]

ENTITIES = [
    {
        'id': 'cap.db.read',
        'type': 'capability',
        'pack_id': 'pack.22',
        'name': 'Database Read',
        'description': 'Read data from a database within scope and tenant isolation boundaries.',
        'risk_tier': 'low',
        'tags': ['database', 'read', 'data-plane'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.obs.structured-logging'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.db.write',
        'type': 'capability',
        'pack_id': 'pack.22',
        'name': 'Database Write',
        'description': 'Write or update data in a database with transaction and audit guarantees.',
        'risk_tier': 'medium',
        'tags': ['database', 'write', 'data-plane'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 2,
            'network': 0,
            'financial': 1,
            'time': 1,
            'reversibility': 'partially-reversible',
        },
        'typical_controls': ['ctrl.obs.structured-logging', 'ctrl.obs.audit-log-append-only'],
        'idempotency': 'partial',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.db.migrate',
        'type': 'capability',
        'pack_id': 'pack.22',
        'name': 'Database Migration',
        'description': 'Apply a versioned schema migration with dry-run, canary, and rollback support.',
        'risk_tier': 'critical',
        'tags': ['database', 'migrations', 'schema'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 4,
            'network': 0,
            'financial': 2,
            'time': 4,
            'reversibility': 'partially-reversible',
        },
        'typical_controls': ['ctrl.obs.audit-log-append-only', 'ctrl.obs.structured-logging'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.db.backfill',
        'type': 'capability',
        'pack_id': 'pack.22',
        'name': 'Database Backfill',
        'description': 'Backfill existing records with new computed fields using throttled, resumable batch processing.',
        'risk_tier': 'high',
        'tags': ['database', 'backfill', 'migrations'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 3,
            'network': 0,
            'financial': 1,
            'time': 4,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.obs.structured-logging', 'ctrl.obs.metrics-core'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.db.reconcile',
        'type': 'capability',
        'pack_id': 'pack.22',
        'name': 'Database Reconcile',
        'description': 'Compare source-of-truth against derived projections and repair inconsistencies.',
        'risk_tier': 'high',
        'tags': ['database', 'consistency', 'reconcile'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 3,
            'network': 0,
            'financial': 1,
            'time': 2,
            'reversibility': 'partially-reversible',
        },
        'typical_controls': ['ctrl.obs.audit-log-append-only', 'ctrl.obs.structured-logging'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'wrk.db.migration.worker',
        'type': 'worker_species',
        'pack_id': 'pack.22',
        'name': 'Database Migration Worker',
        'description': 'Schema migrations/backfills with canary, throttling, and checkpoints.',
        'risk_tier': 'critical',
        'level': 'L5',
        'guarantee': 'exactly-once',
        'determinism': 'deterministic',
        'blast_score': None,
        'required_controls': ['ctrl.obs.audit-log-append-only', 'ctrl.obs.structured-logging'],
        'handles_capabilities': ['cap.db.migrate', 'cap.db.backfill'],
        'tags': ['database', 'migrations'],
        'serves_capabilities': ['cap.db.migrate', 'cap.db.backfill'],
        'blast_radius_hint': {
            'data': 4,
            'network': 0,
            'financial': 2,
            'time': 4,
            'reversibility': 'partially-reversible',
        },
        'idempotency': 'full',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'wrk.db.reconciler',
        'type': 'worker_species',
        'pack_id': 'pack.22',
        'name': 'Database Reconciler Worker',
        'description': 'Compare source-of-truth vs derived projections; repair drift with audit.',
        'risk_tier': 'medium',
        'level': 'L4',
        'guarantee': 'at-least-once',
        'determinism': 'deterministic',
        'blast_score': None,
        'required_controls': ['ctrl.obs.structured-logging'],
        'handles_capabilities': ['cap.db.reconcile'],
        'tags': ['database', 'consistency'],
        'serves_capabilities': ['cap.db.reconcile'],
        'blast_radius_hint': {
            'data': 2,
            'network': 0,
            'financial': 0,
            'time': 2,
            'reversibility': 'partially-reversible',
        },
        'idempotency': 'full',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.db.migration-safe',
        'type': 'profile',
        'pack_id': 'pack.22',
        'name': 'Safe DB Migration Profile',
        'description': 'Safe migration posture: dry-run first, canary rollout, full audit, rollback checkpoint.',
        'tags': ['database', 'migrations', 'safety'],
        'controls_required': ['ctrl.obs.audit-log-append-only', 'ctrl.obs.structured-logging', 'ctrl.obs.run-metadata-store'],
        'recommended_for_risk_tiers': ['medium', 'high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.db.reconciliation-strict',
        'type': 'profile',
        'pack_id': 'pack.22',
        'name': 'Strict Reconciliation DB Profile',
        'description': 'Strict reconciliation posture: continuous drift detection, repair-on-detect, full audit.',
        'tags': ['database', 'consistency', 'strict'],
        'controls_required': ['ctrl.obs.audit-log-append-only', 'ctrl.obs.structured-logging', 'ctrl.obs.metrics-core'],
        'recommended_for_risk_tiers': ['high', 'critical'],
        'wcp_namespace': 'reserved',
    },
]
