"""Pack 11: Notification / Deliverability"""

PACKS = [
    {
        "id": "pack.11",
        "name": "Notification / Deliverability",
        "entity_count": 8,
    },
]

ENTITIES = [
    # --- Capabilities ---
    {
        "id": "cap.notify.send_email",
        "type": "capability",
        "pack_id": "pack.11",
        "name": "Send Email",
        "description": "Send a transactional or notification email via configured email provider.",
        "risk_tier": "medium",
        "tags": ["notifications", "email", "egress"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 2, "financial": 1, "time": 1, "reversibility": "irreversible"},
        "typical_controls": ["ctrl.obs.structured_logging", "ctrl.obs.metrics_core"],
        "idempotency": "partial",
        "determinism": "captured",
    },
    {
        "id": "cap.notify.send_sms",
        "type": "capability",
        "pack_id": "pack.11",
        "name": "Send SMS",
        "description": "Send an SMS notification via configured telephony provider.",
        "risk_tier": "medium",
        "tags": ["notifications", "sms", "egress"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 2, "financial": 2, "time": 1, "reversibility": "irreversible"},
        "typical_controls": ["ctrl.obs.structured_logging", "ctrl.obs.metrics_core"],
        "idempotency": "partial",
        "determinism": "captured",
    },
    {
        "id": "cap.notify.send_push",
        "type": "capability",
        "pack_id": "pack.11",
        "name": "Send Push Notification",
        "description": "Send a push notification to a mobile/web device via push provider.",
        "risk_tier": "low",
        "tags": ["notifications", "push", "egress"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 2, "financial": 0, "time": 1, "reversibility": "irreversible"},
        "typical_controls": ["ctrl.obs.structured_logging"],
        "idempotency": "partial",
        "determinism": "captured",
    },
    {
        "id": "cap.notify.manage_suppression",
        "type": "capability",
        "pack_id": "pack.11",
        "name": "Manage Suppression Lists",
        "description": "Add, remove, or query suppression list entries (unsubscribes, bounces, complaints).",
        "risk_tier": "medium",
        "tags": ["notifications", "suppression", "compliance"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only", "ctrl.obs.structured_logging"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    # --- Worker Species ---
    {
        "id": "wrk.notify.delivery.worker",
        "type": "worker_species",
        "pack_id": "pack.11",
        "name": "Notification Delivery Worker",
        "description": "Send email/SMS/push with deliverability controls and idempotency.",
        "risk_tier": "medium",
        "level": "L4",
        "guarantee": "at-least-once",
        "determinism": "captured-deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.structured_logging",
            "ctrl.obs.metrics_core",
        ],
        "handles_capabilities": [
            "cap.notify.send_email",
            "cap.notify.send_sms",
            "cap.notify.send_push",
        ],
        "tags": ["notifications", "egress"],
        "serves_capabilities": ["cap.notify.send_email", "cap.notify.send_sms", "cap.notify.send_push"],
        "blast_radius_hint": {"data": 1, "network": 2, "financial": 2, "time": 1, "reversibility": "irreversible"},
        "idempotency": "partial",
    },
    {
        "id": "wrk.notify.webhook.ingest",
        "type": "worker_species",
        "pack_id": "pack.11",
        "name": "Notification Webhook Ingest Worker",
        "description": "Ingest provider webhooks (bounces/complaints), update suppression.",
        "risk_tier": "medium",
        "level": "L4",
        "guarantee": "at-least-once",
        "determinism": "deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.structured_logging",
        ],
        "handles_capabilities": [
            "cap.notify.manage_suppression",
        ],
        "tags": ["notifications", "webhooks"],
        "serves_capabilities": ["cap.notify.manage_suppression"],
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 0, "time": 0, "reversibility": "reversible"},
        "idempotency": "full",
    },
    # --- Profiles ---
    {
        "id": "prof.notify.standard",
        "type": "profile",
        "pack_id": "pack.11",
        "name": "Standard Notification Profile",
        "description": "Standard notification posture with deliverability logging and suppression checks.",
        "tags": ["notifications", "standard"],
        "controls_required": [
            "ctrl.obs.structured_logging",
            "ctrl.obs.metrics_core",
        ],
        "recommended_for_risk_tiers": ["low", "medium"],
    },
    {
        "id": "prof.notify.compliance_strict",
        "type": "profile",
        "pack_id": "pack.11",
        "name": "Strict Compliance Notification Profile",
        "description": "Strict notification posture for regulated channels: audit, suppression, and consent enforcement.",
        "tags": ["notifications", "compliance", "strict"],
        "controls_required": [
            "ctrl.obs.audit_log_append_only",
            "ctrl.obs.structured_logging",
            "ctrl.obs.metrics_core",
        ],
        "recommended_for_risk_tiers": ["high", "critical"],
    },
]
