"""Pack source — pack_26_workforce_os"""

PACKS = [
    {
        'id': 'pack.26',
        'name': 'Workforce OS (Meta-Worker: Composition, Routing, Governance)',
        'entity_count': 20,
    },
]

ENTITIES = [
    {
        'id': 'cap.os.register-worker',
        'type': 'capability',
        'pack_id': 'pack.26',
        'name': 'Register Worker',
        'description': 'Enroll a worker into the workforce registry with validated controls and provenance.',
        'risk_tier': 'high',
        'tags': ['workforce-os', 'registry', 'governance'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.os.worker-registry', 'ctrl.obs.audit-log-append-only'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.os.route-task',
        'type': 'capability',
        'pack_id': 'pack.26',
        'name': 'Route Task',
        'description': 'Route a task to the appropriate worker using deterministic routing rules.',
        'risk_tier': 'high',
        'tags': ['workforce-os', 'routing', 'orchestration'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 1,
            'financial': 1,
            'time': 1,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.os.routing-rules', 'ctrl.os.policy-gate-every-step'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.os.compose-workflow',
        'type': 'capability',
        'pack_id': 'pack.26',
        'name': 'Compose Workflow',
        'description': 'Compose multi-worker workflows with policy gates, cost controls, and provenance.',
        'risk_tier': 'high',
        'tags': ['workforce-os', 'composition', 'orchestration'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 2,
            'network': 2,
            'financial': 2,
            'time': 2,
            'reversibility': 'partially-reversible',
        },
        'typical_controls': ['ctrl.os.routing-rules', 'ctrl.os.end-to-end-correlation'],
        'idempotency': 'partial',
        'determinism': 'captured',
    },
    {
        'id': 'cap.os.enforce-policies',
        'type': 'capability',
        'pack_id': 'pack.26',
        'name': 'Enforce Policies',
        'description': 'Enforce workforce-wide policies (budget, data label, QoS, privileges) at every routing step.',
        'risk_tier': 'critical',
        'tags': ['workforce-os', 'policy', 'governance'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 1,
            'financial': 2,
            'time': 0,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.os.policy-gate-every-step', 'ctrl.pol.default-deny'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.os.observe-end-to-end',
        'type': 'capability',
        'pack_id': 'pack.26',
        'name': 'Observe End-to-End',
        'description': 'Collect end-to-end telemetry with correlation_id across all workers in a request.',
        'risk_tier': 'medium',
        'tags': ['workforce-os', 'observability', 'tracing'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 0,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.os.end-to-end-correlation', 'ctrl.obs.tracing-distributed'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.os.emergency-controls',
        'type': 'capability',
        'pack_id': 'pack.26',
        'name': 'Emergency Controls',
        'description': 'Activate global or per-worker kill switches for emergency shutdown or quarantine.',
        'risk_tier': 'critical',
        'tags': ['workforce-os', 'emergency', 'safety'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 0,
            'network': 4,
            'financial': 3,
            'time': 3,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.os.global-kill-switches', 'ctrl.obs.audit-log-append-only'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.os.govern-worker-lifecycle',
        'type': 'capability',
        'pack_id': 'pack.26',
        'name': 'Govern Worker Lifecycle',
        'description': 'Manage worker enrollment, suspension, retirement, and version transitions.',
        'risk_tier': 'high',
        'tags': ['workforce-os', 'lifecycle', 'governance'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 1,
            'financial': 1,
            'time': 2,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.os.worker-registry', 'ctrl.obs.audit-log-append-only'],
        'idempotency': 'partial',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.os.memory-and-context-service',
        'type': 'capability',
        'pack_id': 'pack.26',
        'name': 'Memory and Context Service',
        'description': 'Provide memory and context services to workers (scoped retrieval, embedding, summarization).',
        'risk_tier': 'medium',
        'tags': ['workforce-os', 'memory', 'context'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 1,
            'financial': 1,
            'time': 1,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.obs.structured-logging', 'ctrl.cost.monthly-token-budget'],
        'idempotency': 'partial',
        'determinism': 'non-deterministic',
    },
    {
        'id': 'wrk.os.workforce-router',
        'type': 'worker_species',
        'pack_id': 'pack.26',
        'name': 'Workforce Router Worker',
        'description': 'Route, compose, and govern across all workers; enforce policies, budgets, QoS, and provenance.',
        'risk_tier': 'critical',
        'level': 'L8',
        'guarantee': 'exactly-once',
        'determinism': 'deterministic',
        'blast_score': None,
        'required_controls': ['ctrl.os.worker-registry', 'ctrl.os.routing-rules', 'ctrl.os.policy-gate-every-step', 'ctrl.os.end-to-end-correlation', 'ctrl.os.global-kill-switches'],
        'handles_capabilities': ['cap.os.route_task', 'cap.os.compose_workflow', 'cap.os.enforce_policies'],
        'tags': ['workforce-os', 'routing', 'governance'],
        'serves_capabilities': ['cap.os.route-task', 'cap.os.compose-workflow', 'cap.os.enforce-policies'],
        'blast_radius_hint': {
            'data': 2,
            'network': 4,
            'financial': 3,
            'time': 3,
            'reversibility': 'partially-reversible',
        },
        'idempotency': 'full',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'wrk.os.registry-manager',
        'type': 'worker_species',
        'pack_id': 'pack.26',
        'name': 'Registry Manager Worker',
        'description': 'Maintain worker registry; enroll/retire; validate controls and provenance.',
        'risk_tier': 'high',
        'level': 'L6',
        'guarantee': 'exactly-once',
        'determinism': 'deterministic',
        'blast_score': None,
        'required_controls': ['ctrl.os.worker-registry', 'ctrl.obs.audit-log-append-only'],
        'handles_capabilities': ['cap.os.register_worker', 'cap.os.govern_worker_lifecycle'],
        'tags': ['workforce-os', 'registry'],
        'serves_capabilities': ['cap.os.register-worker', 'cap.os.govern-worker-lifecycle'],
        'blast_radius_hint': {
            'data': 1,
            'network': 0,
            'financial': 0,
            'time': 1,
            'reversibility': 'reversible',
        },
        'idempotency': 'full',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'wrk.os.incident-commander',
        'type': 'worker_species',
        'pack_id': 'pack.26',
        'name': 'Incident Commander Worker',
        'description': 'Coordinate incident mode: kill switches, quarantine, runbooks, evidence bundles.',
        'risk_tier': 'critical',
        'level': 'L7',
        'guarantee': 'at-least-once',
        'determinism': 'nondeterministic',
        'blast_score': None,
        'required_controls': ['ctrl.os.global-kill-switches', 'ctrl.obs.audit-log-append-only'],
        'handles_capabilities': ['cap.os.emergency_controls'],
        'tags': ['workforce-os', 'incident', 'emergency'],
        'serves_capabilities': ['cap.os.emergency-controls'],
        'blast_radius_hint': {
            'data': 0,
            'network': 4,
            'financial': 3,
            'time': 3,
            'reversibility': 'reversible',
        },
        'idempotency': 'full',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.os.worker-registry',
        'type': 'control',
        'pack_id': 'pack.26',
        'name': 'Worker Registry',
        'description': 'Maintain an enrolled worker registry; deny execution for unregistered workers.',
        'tags': ['workforce-os', 'registry', 'governance'],
        'enforcement_point': 'hall',
        'required_for_risk_tiers': ['low', 'medium', 'high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.os.routing-rules',
        'type': 'control',
        'pack_id': 'pack.26',
        'name': 'Deterministic Routing Rules',
        'description': 'Enforce deterministic, versioned routing rules (first-match-wins).',
        'tags': ['workforce-os', 'routing'],
        'enforcement_point': 'hall',
        'required_for_risk_tiers': ['medium', 'high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.os.policy-gate-every-step',
        'type': 'control',
        'pack_id': 'pack.26',
        'name': 'Policy Gate Every Step',
        'description': 'Apply policy gate at every routing step, not just pre-run.',
        'tags': ['workforce-os', 'policy', 'governance'],
        'enforcement_point': 'hall',
        'required_for_risk_tiers': ['high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.os.end-to-end-correlation',
        'type': 'control',
        'pack_id': 'pack.26',
        'name': 'End-to-End Correlation',
        'description': 'Propagate correlation_id across every worker call, tool call, and telemetry event.',
        'tags': ['workforce-os', 'observability', 'tracing'],
        'enforcement_point': 'worker',
        'required_for_risk_tiers': ['medium', 'high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.os.global-kill-switches',
        'type': 'control',
        'pack_id': 'pack.26',
        'name': 'Global Kill Switches',
        'description': 'Global and per-worker kill switches for emergency shutdown.',
        'tags': ['workforce-os', 'emergency', 'safety'],
        'enforcement_point': 'platform',
        'required_for_risk_tiers': ['medium', 'high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.os.budget-and-cost-enforcement',
        'type': 'control',
        'pack_id': 'pack.26',
        'name': 'Budget and Cost Enforcement',
        'description': 'Enforce per-agent, per-tenant cost caps and budgets.',
        'tags': ['workforce-os', 'cost', 'governance'],
        'enforcement_point': 'hall',
        'required_for_risk_tiers': ['medium', 'high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.os.provenance-requirements',
        'type': 'control',
        'pack_id': 'pack.26',
        'name': 'Provenance Requirements',
        'description': 'Require signed provenance for all production worker executions.',
        'tags': ['workforce-os', 'provenance', 'supply-chain'],
        'enforcement_point': 'hall',
        'required_for_risk_tiers': ['high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.os.production-control-plane',
        'type': 'profile',
        'pack_id': 'pack.26',
        'name': 'Production Control Plane Profile',
        'description': 'Production workforce OS posture: registry, routing, policy gates, cost enforcement, provenance.',
        'tags': ['workforce-os', 'production', 'governance'],
        'controls_required': ['ctrl.os.worker-registry', 'ctrl.os.routing-rules', 'ctrl.os.policy-gate-every-step', 'ctrl.os.end-to-end-correlation', 'ctrl.os.budget-and-cost-enforcement', 'ctrl.os.provenance-requirements'],
        'recommended_for_risk_tiers': ['high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.os.incident-mode',
        'type': 'profile',
        'pack_id': 'pack.26',
        'name': 'OS Incident Mode Profile',
        'description': 'Incident mode workforce OS posture: kill switches active, forensic logging, restricted routing.',
        'tags': ['workforce-os', 'incident', 'emergency'],
        'controls_required': ['ctrl.os.global-kill-switches', 'ctrl.obs.audit-log-append-only', 'ctrl.obs.flight-recorder-bundle'],
        'recommended_for_risk_tiers': ['high', 'critical'],
        'wcp_namespace': 'reserved',
    },
]
