"""Pack source — pack_20_memory"""

ENTITIES = [
    {
        'id': 'cap.mem.write',
        'type': 'capability',
        'name': 'Write Memory',
        'description': 'Store a memory artifact (embedding, document, structured record) under a scoped key.',
        'risk_tier': 'medium',
        'tags': [
            'memory',
            'storage',
            'context',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 2,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.obs.audit-log-append-only',
            'ctrl.obs.structured-logging',
        ],
        'idempotency': 'partial',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.mem.read',
        'type': 'capability',
        'name': 'Read Memory',
        'description': 'Retrieve a memory artifact by key or query within scope and access controls.',
        'risk_tier': 'low',
        'tags': [
            'memory',
            'retrieval',
            'context',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
        ],
        'idempotency': 'full',
        'determinism': 'non-deterministic',
    },
    {
        'id': 'cap.mem.delete',
        'type': 'capability',
        'name': 'Delete Memory',
        'description': 'Delete one or more memory artifacts; emit deletion audit record.',
        'risk_tier': 'high',
        'tags': [
            'memory',
            'deletion',
            'privacy',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 3,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'irreversible',
        },
        'typical_controls': [
            'ctrl.obs.audit-log-append-only',
        ],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.mem.embed',
        'type': 'capability',
        'name': 'Embed Text',
        'description': 'Convert text to a vector embedding using a configured embedding model.',
        'risk_tier': 'low',
        'tags': [
            'memory',
            'embeddings',
            'ml',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 0,
            'network': 1,
            'financial': 1,
            'time': 1,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
        ],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.mem.summarize',
        'type': 'capability',
        'name': 'Summarize Context',
        'description': 'Summarize a long context window to a bounded token representation preserving provenance.',
        'risk_tier': 'low',
        'tags': [
            'memory',
            'summarization',
            'context',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 1,
            'financial': 1,
            'time': 1,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
        ],
        'idempotency': 'partial',
        'determinism': 'non-deterministic',
    },
    {
        'id': 'cap.mem.retrieve.rag',
        'type': 'capability',
        'name': 'RAG Retrieval',
        'description': 'Retrieve relevant memory chunks via hybrid vector + keyword search for RAG pipelines.',
        'risk_tier': 'low',
        'tags': [
            'memory',
            'rag',
            'retrieval',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 1,
            'financial': 1,
            'time': 1,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
        ],
        'idempotency': 'full',
        'determinism': 'non-deterministic',
    },
    {
        'id': 'wrk.mem.retriever',
        'type': 'worker_species',
        'name': 'Memory Retriever Worker',
        'description': 'Retrieve memory/document chunks under scope filters and token budgets.',
        'risk_tier': 'low',
        'determinism': 'nondeterministic',
        'required_controls': [
            'ctrl.obs.structured-logging',
        ],
        'tags': [
            'memory',
            'rag',
            'retrieval',
        ],
        'serves_capabilities': [
            'cap.mem.retrieve.rag',
            'cap.mem.read',
        ],
        'blast_radius_hint': {
            'data': 1,
            'network': 1,
            'financial': 1,
            'time': 1,
            'reversibility': 'reversible',
        },
        'idempotency': 'full',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'wrk.mem.curator',
        'type': 'worker_species',
        'name': 'Memory Curator Worker',
        'description': 'Decide what gets stored; apply redaction, TTL, provenance; prevent poisoning.',
        'risk_tier': 'high',
        'determinism': 'deterministic',
        'required_controls': [
            'ctrl.obs.audit-log-append-only',
            'ctrl.obs.structured-logging',
        ],
        'tags': [
            'memory',
            'privacy',
            'safety',
        ],
        'serves_capabilities': [
            'cap.mem.write',
            'cap.mem.delete',
        ],
        'blast_radius_hint': {
            'data': 3,
            'network': 0,
            'financial': 0,
            'time': 1,
            'reversibility': 'partially-reversible',
        },
        'idempotency': 'partial',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'wrk.mem.summarizer',
        'type': 'worker_species',
        'name': 'Memory Summarizer Worker',
        'description': 'Summarize long context to bounded tokens preserving provenance.',
        'risk_tier': 'low',
        'determinism': 'nondeterministic',
        'required_controls': [
            'ctrl.obs.structured-logging',
        ],
        'tags': [
            'memory',
            'summarization',
            'ml',
        ],
        'serves_capabilities': [
            'cap.mem.summarize',
            'cap.mem.embed',
        ],
        'blast_radius_hint': {
            'data': 1,
            'network': 1,
            'financial': 1,
            'time': 1,
            'reversibility': 'reversible',
        },
        'idempotency': 'partial',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.mem.rag-strict-scoped',
        'type': 'profile',
        'name': 'Strict Scoped RAG Profile',
        'description': 'Strict RAG posture: scoped retrieval, token budget enforcement, no cross-tenant leakage.',
        'tags': [
            'memory',
            'rag',
            'privacy',
        ],
        'controls_required': [
            'ctrl.obs.structured-logging',
            'ctrl.cost.monthly-token-budget',
        ],
        'recommended_for_risk_tiers': [
            'medium',
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.mem.privacy-conservative',
        'type': 'profile',
        'name': 'Privacy-Conservative Memory Profile',
        'description': 'Privacy-conservative memory posture: minimal retention, aggressive TTLs, deletion audit.',
        'tags': [
            'memory',
            'privacy',
            'gdpr',
        ],
        'controls_required': [
            'ctrl.obs.audit-log-append-only',
            'ctrl.obs.structured-logging',
        ],
        'recommended_for_risk_tiers': [
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.mem.budgeted-summaries',
        'type': 'profile',
        'name': 'Budgeted Summaries Memory Profile',
        'description': 'Cost-conscious memory posture: summarization-first, token budget enforcement.',
        'tags': [
            'memory',
            'cost',
            'summarization',
        ],
        'controls_required': [
            'ctrl.obs.structured-logging',
            'ctrl.cost.monthly-token-budget',
        ],
        'recommended_for_risk_tiers': [
            'low',
            'medium',
        ],
        'wcp_namespace': 'reserved',
    },
]
