"""Pack 02: Secrets, Identity & Credential Hygiene"""

PACKS = [
    {
        "id": "pack.02",
        "name": "Secrets, Identity & Credential Hygiene",
        "entity_count": 5,
    },
]

ENTITIES = [
    {
        "id": "cap.identity.workload",
        "type": "capability",
        "pack_id": "pack.02",
        "name": "Workload Identity",
        "description": "Assert a cryptographic workload identity bound to the execution context.",
        "risk_tier": "high",
        "tags": ["identity", "security", "credentials"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 1, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.sandbox.secrets_denied_by_default"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.secrets.read",
        "type": "capability",
        "pack_id": "pack.02",
        "name": "Read Secrets",
        "description": "Read secrets from a secrets vault scoped to the workload identity.",
        "risk_tier": "high",
        "tags": ["secrets", "security", "credentials"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 3, "network": 1, "financial": 2, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.sandbox.secrets_denied_by_default", "ctrl.obs.audit_log_append_only"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.token.mint.shortlived",
        "type": "capability",
        "pack_id": "pack.02",
        "name": "Mint Short-Lived Token",
        "description": "Mint a short-lived access token (TTL <= 1 hour) scoped to specific resources.",
        "risk_tier": "high",
        "tags": ["identity", "tokens", "security"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 1, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.sandbox.secrets_denied_by_default", "ctrl.obs.audit_log_append_only"],
        "idempotency": "partial",
        "determinism": "deterministic",
    },
    {
        "id": "cap.credential.rotate",
        "type": "capability",
        "pack_id": "pack.02",
        "name": "Rotate Credentials",
        "description": "Rotate a credential (API key, certificate, secret) and update all references.",
        "risk_tier": "high",
        "tags": ["credentials", "rotation", "security"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 2, "network": 2, "financial": 2, "time": 2, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only", "ctrl.sandbox.secrets_denied_by_default"],
        "idempotency": "partial",
        "determinism": "deterministic",
    },
    {
        "id": "cap.audit.read",
        "type": "capability",
        "pack_id": "pack.02",
        "name": "Read Audit Logs",
        "description": "Read audit log entries for compliance review and forensic analysis.",
        "risk_tier": "medium",
        "tags": ["audit", "compliance", "security"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
]
