"""Pack 20: Memory & Context Management"""

PACKS = [
    {
        "id": "pack.20",
        "name": "Memory & Context Management",
        "entity_count": 12,
    },
]

ENTITIES = [
    # --- Capabilities ---
    {
        "id": "cap.mem.write",
        "type": "capability",
        "pack_id": "pack.20",
        "name": "Write Memory",
        "description": "Store a memory artifact (embedding, document, structured record) under a scoped key.",
        "risk_tier": "medium",
        "tags": ["memory", "storage", "context"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 2, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only", "ctrl.obs.structured_logging"],
        "idempotency": "partial",
        "determinism": "deterministic",
    },
    {
        "id": "cap.mem.read",
        "type": "capability",
        "pack_id": "pack.20",
        "name": "Read Memory",
        "description": "Retrieve a memory artifact by key or query within scope and access controls.",
        "risk_tier": "low",
        "tags": ["memory", "retrieval", "context"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging"],
        "idempotency": "full",
        "determinism": "non-deterministic",
    },
    {
        "id": "cap.mem.delete",
        "type": "capability",
        "pack_id": "pack.20",
        "name": "Delete Memory",
        "description": "Delete one or more memory artifacts; emit deletion audit record.",
        "risk_tier": "high",
        "tags": ["memory", "deletion", "privacy"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 3, "network": 0, "financial": 0, "time": 0, "reversibility": "irreversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.mem.embed",
        "type": "capability",
        "pack_id": "pack.20",
        "name": "Embed Text",
        "description": "Convert text to a vector embedding using a configured embedding model.",
        "risk_tier": "low",
        "tags": ["memory", "embeddings", "ml"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 1, "financial": 1, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.mem.summarize",
        "type": "capability",
        "pack_id": "pack.20",
        "name": "Summarize Context",
        "description": "Summarize a long context window to a bounded token representation preserving provenance.",
        "risk_tier": "low",
        "tags": ["memory", "summarization", "context"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 1, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging"],
        "idempotency": "partial",
        "determinism": "non-deterministic",
    },
    {
        "id": "cap.mem.retrieve.rag",
        "type": "capability",
        "pack_id": "pack.20",
        "name": "RAG Retrieval",
        "description": "Retrieve relevant memory chunks via hybrid vector + keyword search for RAG pipelines.",
        "risk_tier": "low",
        "tags": ["memory", "rag", "retrieval"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 1, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging"],
        "idempotency": "full",
        "determinism": "non-deterministic",
    },
    # --- Worker Species ---
    {
        "id": "wrk.mem.retriever",
        "type": "worker_species",
        "pack_id": "pack.20",
        "name": "Memory Retriever Worker",
        "description": "Retrieve memory/document chunks under scope filters and token budgets.",
        "risk_tier": "low",
        "level": "L4",
        "guarantee": "best-effort",
        "determinism": "nondeterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.structured_logging",
        ],
        "handles_capabilities": [
            "cap.mem.retrieve.rag",
            "cap.mem.read",
        ],
        "tags": ["memory", "rag", "retrieval"],
        "serves_capabilities": ["cap.mem.retrieve.rag", "cap.mem.read"],
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 1, "time": 1, "reversibility": "reversible"},
        "idempotency": "full",
    },
    {
        "id": "wrk.mem.curator",
        "type": "worker_species",
        "pack_id": "pack.20",
        "name": "Memory Curator Worker",
        "description": "Decide what gets stored; apply redaction, TTL, provenance; prevent poisoning.",
        "risk_tier": "high",
        "level": "L5",
        "guarantee": "at-least-once",
        "determinism": "deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.audit_log_append_only",
            "ctrl.obs.structured_logging",
        ],
        "handles_capabilities": [
            "cap.mem.write",
            "cap.mem.delete",
        ],
        "tags": ["memory", "privacy", "safety"],
        "serves_capabilities": ["cap.mem.write", "cap.mem.delete"],
        "blast_radius_hint": {"data": 3, "network": 0, "financial": 0, "time": 1, "reversibility": "partially-reversible"},
        "idempotency": "partial",
    },
    {
        "id": "wrk.mem.summarizer",
        "type": "worker_species",
        "pack_id": "pack.20",
        "name": "Memory Summarizer Worker",
        "description": "Summarize long context to bounded tokens preserving provenance.",
        "risk_tier": "low",
        "level": "L4",
        "guarantee": "best-effort",
        "determinism": "nondeterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.structured_logging",
        ],
        "handles_capabilities": [
            "cap.mem.summarize",
            "cap.mem.embed",
        ],
        "tags": ["memory", "summarization", "ml"],
        "serves_capabilities": ["cap.mem.summarize", "cap.mem.embed"],
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 1, "time": 1, "reversibility": "reversible"},
        "idempotency": "partial",
    },
    # --- Profiles ---
    {
        "id": "prof.mem.rag_strict_scoped",
        "type": "profile",
        "pack_id": "pack.20",
        "name": "Strict Scoped RAG Profile",
        "description": "Strict RAG posture: scoped retrieval, token budget enforcement, no cross-tenant leakage.",
        "tags": ["memory", "rag", "privacy"],
        "controls_required": [
            "ctrl.obs.structured_logging",
            "ctrl.cost.monthly_token_budget",
        ],
        "recommended_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "prof.mem.privacy_conservative",
        "type": "profile",
        "pack_id": "pack.20",
        "name": "Privacy-Conservative Memory Profile",
        "description": "Privacy-conservative memory posture: minimal retention, aggressive TTLs, deletion audit.",
        "tags": ["memory", "privacy", "gdpr"],
        "controls_required": [
            "ctrl.obs.audit_log_append_only",
            "ctrl.obs.structured_logging",
        ],
        "recommended_for_risk_tiers": ["high", "critical"],
    },
    {
        "id": "prof.mem.budgeted_summaries",
        "type": "profile",
        "pack_id": "pack.20",
        "name": "Budgeted Summaries Memory Profile",
        "description": "Cost-conscious memory posture: summarization-first, token budget enforcement.",
        "tags": ["memory", "cost", "summarization"],
        "controls_required": [
            "ctrl.obs.structured_logging",
            "ctrl.cost.monthly_token_budget",
        ],
        "recommended_for_risk_tiers": ["low", "medium"],
    },
]
