"""Pack source — pack_21_workflow"""

PACKS = [
    {
        'id': 'pack.21',
        'name': 'Workflow Orchestration (DAGs, Checkpoints, Sagas)',
        'entity_count': 8,
    },
]

ENTITIES = [
    {
        'id': 'cap.wf.define-dag',
        'type': 'capability',
        'pack_id': 'pack.21',
        'name': 'Define Workflow DAG',
        'description': 'Define a directed acyclic graph of workflow steps with dependencies and data flows.',
        'risk_tier': 'medium',
        'tags': ['workflows', 'dag', 'orchestration'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 0,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.obs.structured-logging'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.wf.checkpoint',
        'type': 'capability',
        'pack_id': 'pack.21',
        'name': 'Checkpoint Workflow',
        'description': 'Persist workflow execution state at a checkpoint for durable resumption.',
        'risk_tier': 'medium',
        'tags': ['workflows', 'checkpoints', 'durability'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.obs.structured-logging', 'ctrl.obs.run-metadata-store'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.wf.compensate',
        'type': 'capability',
        'pack_id': 'pack.21',
        'name': 'Compensate Workflow',
        'description': 'Execute compensation steps to undo committed actions in a failed saga.',
        'risk_tier': 'high',
        'tags': ['workflows', 'saga', 'compensation'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 3,
            'network': 2,
            'financial': 2,
            'time': 3,
            'reversibility': 'partially-reversible',
        },
        'typical_controls': ['ctrl.obs.audit-log-append-only', 'ctrl.obs.tracing-distributed'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.wf.replay-deterministic',
        'type': 'capability',
        'pack_id': 'pack.21',
        'name': 'Replay Deterministic Workflow',
        'description': 'Replay a workflow from a checkpoint with deterministic step execution for recovery.',
        'risk_tier': 'medium',
        'tags': ['workflows', 'replay', 'recovery'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 2,
            'network': 1,
            'financial': 1,
            'time': 2,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.obs.tracing-distributed', 'ctrl.obs.structured-logging'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.wf.fanout-fanin',
        'type': 'capability',
        'pack_id': 'pack.21',
        'name': 'Fan-Out / Fan-In',
        'description': 'Parallelize workflow steps across multiple workers and aggregate results.',
        'risk_tier': 'medium',
        'tags': ['workflows', 'parallelism', 'aggregation'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 2,
            'financial': 2,
            'time': 2,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.obs.tracing-distributed', 'ctrl.obs.metrics-core'],
        'idempotency': 'partial',
        'determinism': 'captured',
    },
    {
        'id': 'wrk.wf.orchestrator',
        'type': 'worker_species',
        'pack_id': 'pack.21',
        'name': 'Workflow Orchestrator Worker',
        'description': 'Execute durable workflows: schedule steps, checkpoint, retry, compensate.',
        'risk_tier': 'high',
        'level': 'L6',
        'guarantee': 'exactly-once',
        'determinism': 'captured-deterministic',
        'blast_score': None,
        'required_controls': ['ctrl.obs.audit-log-append-only', 'ctrl.obs.tracing-distributed'],
        'handles_capabilities': ['cap.wf.define_dag', 'cap.wf.checkpoint', 'cap.wf.compensate', 'cap.wf.fanout_fanin'],
        'tags': ['workflows', 'orchestration', 'sagas'],
        'serves_capabilities': ['cap.wf.define-dag', 'cap.wf.checkpoint', 'cap.wf.compensate', 'cap.wf.fanout-fanin'],
        'blast_radius_hint': {
            'data': 3,
            'network': 2,
            'financial': 2,
            'time': 3,
            'reversibility': 'partially-reversible',
        },
        'idempotency': 'partial',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'wrk.wf.step.executor',
        'type': 'worker_species',
        'pack_id': 'pack.21',
        'name': 'Workflow Step Executor Worker',
        'description': 'Execute a single workflow step under idempotency keys.',
        'risk_tier': 'medium',
        'level': 'L4',
        'guarantee': 'at-least-once',
        'determinism': 'deterministic',
        'blast_score': None,
        'required_controls': ['ctrl.obs.structured-logging'],
        'handles_capabilities': ['cap.wf.replay_deterministic'],
        'tags': ['workflows', 'idempotency'],
        'serves_capabilities': ['cap.wf.replay-deterministic'],
        'blast_radius_hint': {
            'data': 1,
            'network': 1,
            'financial': 1,
            'time': 1,
            'reversibility': 'reversible',
        },
        'idempotency': 'full',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.wf.durable-saga',
        'type': 'profile',
        'pack_id': 'pack.21',
        'name': 'Durable Saga Workflow Profile',
        'description': 'Durable saga posture: checkpoints, compensations, exactly-once semantics, distributed tracing.',
        'tags': ['workflows', 'saga', 'durability'],
        'controls_required': ['ctrl.obs.audit-log-append-only', 'ctrl.obs.tracing-distributed', 'ctrl.obs.run-metadata-store'],
        'recommended_for_risk_tiers': ['medium', 'high', 'critical'],
        'wcp_namespace': 'reserved',
    },
]
