"""Pack 13: Chaos / Fault Injection"""

PACKS = [
    {
        "id": "pack.13",
        "name": "Chaos / Fault Injection",
        "entity_count": 7,
    },
]

ENTITIES = [
    # --- Capabilities ---
    {
        "id": "cap.chaos.inject_latency",
        "type": "capability",
        "pack_id": "pack.13",
        "name": "Inject Latency",
        "description": "Inject artificial latency into specified service paths for resilience testing.",
        "risk_tier": "high",
        "tags": ["chaos", "latency", "resilience"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 3, "financial": 1, "time": 3, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.slo_alerting", "ctrl.obs.metrics_core"],
        "idempotency": "partial",
        "determinism": "non-deterministic",
    },
    {
        "id": "cap.chaos.inject_errors",
        "type": "capability",
        "pack_id": "pack.13",
        "name": "Inject Errors",
        "description": "Inject controlled error responses into service paths for failure mode testing.",
        "risk_tier": "high",
        "tags": ["chaos", "errors", "resilience"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 2, "financial": 1, "time": 2, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.slo_alerting", "ctrl.obs.structured_logging"],
        "idempotency": "partial",
        "determinism": "non-deterministic",
    },
    {
        "id": "cap.chaos.disable_dependency",
        "type": "capability",
        "pack_id": "pack.13",
        "name": "Disable Dependency",
        "description": "Temporarily disable or throttle an upstream dependency to test degraded-mode behavior.",
        "risk_tier": "high",
        "tags": ["chaos", "dependencies", "resilience"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 3, "financial": 2, "time": 3, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.slo_alerting", "ctrl.obs.metrics_core"],
        "idempotency": "partial",
        "determinism": "non-deterministic",
    },
    {
        "id": "cap.chaos.poison_messages",
        "type": "capability",
        "pack_id": "pack.13",
        "name": "Poison Queue Messages",
        "description": "Inject malformed or poison-pill messages into a queue to test DLQ and error handling.",
        "risk_tier": "high",
        "tags": ["chaos", "queues", "dlq"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 2, "network": 1, "financial": 1, "time": 2, "reversibility": "partially-reversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only", "ctrl.obs.structured_logging"],
        "idempotency": "partial",
        "determinism": "non-deterministic",
    },
    # --- Worker Species ---
    {
        "id": "wrk.chaos.injector",
        "type": "worker_species",
        "pack_id": "pack.13",
        "name": "Chaos Injector Worker",
        "description": "Apply controlled fault injection per experiment plans and guardrails.",
        "risk_tier": "high",
        "level": "L5",
        "guarantee": "best-effort",
        "determinism": "nondeterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.structured_logging",
            "ctrl.obs.slo_alerting",
        ],
        "handles_capabilities": [
            "cap.chaos.inject_latency",
            "cap.chaos.inject_errors",
            "cap.chaos.poison_messages",
        ],
        "tags": ["chaos", "resilience"],
        "serves_capabilities": ["cap.chaos.inject_latency", "cap.chaos.inject_errors", "cap.chaos.poison_messages"],
        "blast_radius_hint": {"data": 2, "network": 3, "financial": 2, "time": 3, "reversibility": "reversible"},
        "idempotency": "none",
    },
    {
        "id": "wrk.chaos.observer",
        "type": "worker_species",
        "pack_id": "pack.13",
        "name": "Chaos Observer Worker",
        "description": "Collect metrics during experiments; generate reports vs SLO criteria.",
        "risk_tier": "medium",
        "level": "L4",
        "guarantee": "best-effort",
        "determinism": "nondeterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.metrics_core",
            "ctrl.obs.slo_alerting",
        ],
        "handles_capabilities": [],
        "tags": ["chaos", "observability"],
        "serves_capabilities": [],
        "blast_radius_hint": {"data": 0, "network": 1, "financial": 0, "time": 1, "reversibility": "reversible"},
        "idempotency": "partial",
    },
    # --- Profiles ---
    {
        "id": "prof.chaos.canary_scoped",
        "type": "profile",
        "pack_id": "pack.13",
        "name": "Canary-Scoped Chaos Profile",
        "description": "Chaos experiments scoped strictly to canary traffic with SLO guardrails.",
        "tags": ["chaos", "canary", "resilience"],
        "controls_required": [
            "ctrl.obs.slo_alerting",
            "ctrl.obs.metrics_core",
            "ctrl.obs.structured_logging",
        ],
        "recommended_for_risk_tiers": ["medium", "high"],
    },
]
