"""Pack 10: Document Pipeline (PDF/OCR/Redaction/Signing)"""

PACKS = [
    {
        "id": "pack.10",
        "name": "Document Pipeline (PDF/OCR/Redaction/Signing)",
        "entity_count": 14,
    },
]

ENTITIES = [
    # --- Capabilities ---
    {
        "id": "cap.doc.ingest",
        "type": "capability",
        "pack_id": "pack.10",
        "name": "Ingest Document",
        "description": "Ingest a document artifact into the pipeline, validate format, and register provenance.",
        "risk_tier": "medium",
        "tags": ["docs", "ingest", "pipeline"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 0, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging", "ctrl.obs.run_metadata_store"],
        "idempotency": "partial",
        "determinism": "deterministic",
    },
    {
        "id": "cap.doc.ocr",
        "type": "capability",
        "pack_id": "pack.10",
        "name": "OCR Document",
        "description": "Extract text and layout from a document using optical character recognition.",
        "risk_tier": "medium",
        "tags": ["docs", "ocr", "ml"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 0, "financial": 1, "time": 2, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging", "ctrl.obs.metrics_core"],
        "idempotency": "partial",
        "determinism": "non-deterministic",
    },
    {
        "id": "cap.doc.classify",
        "type": "capability",
        "pack_id": "pack.10",
        "name": "Classify Document",
        "description": "Classify a document by type, sensitivity, and routing category.",
        "risk_tier": "medium",
        "tags": ["docs", "classification", "ml"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 0, "financial": 0, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging"],
        "idempotency": "full",
        "determinism": "captured",
    },
    {
        "id": "cap.doc.redact",
        "type": "capability",
        "pack_id": "pack.10",
        "name": "Redact Document",
        "description": "Apply PII/PHI/PCI redactions to a document using rule or ML-based detection.",
        "risk_tier": "high",
        "tags": ["docs", "redaction", "privacy"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 3, "network": 0, "financial": 1, "time": 2, "reversibility": "irreversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only", "ctrl.sandbox.workspace_mounts_only"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.doc.stamp",
        "type": "capability",
        "pack_id": "pack.10",
        "name": "Stamp Document",
        "description": "Apply a visible or invisible processing stamp (watermark, classification label) to a document.",
        "risk_tier": "medium",
        "tags": ["docs", "stamping", "provenance"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 0, "financial": 0, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.doc.sign",
        "type": "capability",
        "pack_id": "pack.10",
        "name": "Sign Document",
        "description": "Apply a cryptographic digital signature to a document artifact using an isolated key.",
        "risk_tier": "critical",
        "tags": ["docs", "signing", "security"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 2, "network": 0, "financial": 2, "time": 1, "reversibility": "irreversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only", "ctrl.sandbox.secrets_denied_by_default"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.doc.hash_artifact",
        "type": "capability",
        "pack_id": "pack.10",
        "name": "Hash Document Artifact",
        "description": "Compute and record the cryptographic hash of a document artifact for integrity verification.",
        "risk_tier": "medium",
        "tags": ["docs", "hashing", "integrity"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.run_metadata_store"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    # --- Worker Species ---
    {
        "id": "wrk.doc.pipeline.orchestrator",
        "type": "worker_species",
        "pack_id": "pack.10",
        "name": "Document Pipeline Orchestrator",
        "description": "Orchestrate multi-step document pipeline with resumability and audit.",
        "risk_tier": "high",
        "level": "L4",
        "guarantee": "at-least-once",
        "determinism": "captured-deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.structured_logging",
            "ctrl.obs.audit_log_append_only",
            "ctrl.sandbox.flight_recorder",
        ],
        "handles_capabilities": [
            "cap.doc.ingest",
            "cap.doc.ocr",
            "cap.doc.classify",
            "cap.doc.stamp",
        ],
        "tags": ["docs", "orchestration"],
        "serves_capabilities": ["cap.doc.ingest", "cap.doc.ocr", "cap.doc.classify", "cap.doc.stamp"],
        "blast_radius_hint": {"data": 3, "network": 1, "financial": 1, "time": 3, "reversibility": "partially-reversible"},
        "idempotency": "partial",
    },
    {
        "id": "wrk.doc.ocr.worker",
        "type": "worker_species",
        "pack_id": "pack.10",
        "name": "OCR Worker",
        "description": "Run OCR and return text and layout with confidence metrics.",
        "risk_tier": "medium",
        "level": "L4",
        "guarantee": "best-effort",
        "determinism": "nondeterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.structured_logging",
            "ctrl.obs.metrics_core",
        ],
        "handles_capabilities": ["cap.doc.ocr"],
        "tags": ["docs", "ocr", "ml"],
        "serves_capabilities": ["cap.doc.ocr"],
        "blast_radius_hint": {"data": 1, "network": 0, "financial": 1, "time": 2, "reversibility": "reversible"},
        "idempotency": "partial",
    },
    {
        "id": "wrk.doc.redaction.worker",
        "type": "worker_species",
        "pack_id": "pack.10",
        "name": "Document Redaction Worker",
        "description": "Apply redactions using templates/rules; emit redaction report.",
        "risk_tier": "high",
        "level": "L4",
        "guarantee": "at-least-once",
        "determinism": "deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.audit_log_append_only",
            "ctrl.sandbox.workspace_mounts_only",
        ],
        "handles_capabilities": ["cap.doc.redact"],
        "tags": ["docs", "redaction"],
        "serves_capabilities": ["cap.doc.redact"],
        "blast_radius_hint": {"data": 3, "network": 0, "financial": 1, "time": 2, "reversibility": "irreversible"},
        "idempotency": "full",
    },
    {
        "id": "wrk.doc.signing.worker",
        "type": "worker_species",
        "pack_id": "pack.10",
        "name": "Document Signing Worker",
        "description": "Apply digital signatures using isolated keys; verify signatures.",
        "risk_tier": "critical",
        "level": "L7",
        "guarantee": "exactly-once",
        "determinism": "deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.audit_log_append_only",
            "ctrl.sandbox.secrets_denied_by_default",
        ],
        "handles_capabilities": ["cap.doc.sign"],
        "tags": ["docs", "signing", "security"],
        "serves_capabilities": ["cap.doc.sign", "cap.doc.hash_artifact"],
        "blast_radius_hint": {"data": 2, "network": 0, "financial": 2, "time": 1, "reversibility": "irreversible"},
        "idempotency": "full",
    },
    # --- Profiles ---
    {
        "id": "prof.doc.untrusted_sandboxed",
        "type": "profile",
        "pack_id": "pack.10",
        "name": "Untrusted Sandboxed Document Profile",
        "description": "Process untrusted/external documents in strict sandboxed environment.",
        "tags": ["docs", "sandbox", "security"],
        "controls_required": [
            "ctrl.sandbox.no_egress_default_deny",
            "ctrl.sandbox.workspace_mounts_only",
            "ctrl.sandbox.resource_limits_strict",
            "ctrl.obs.structured_logging",
        ],
        "recommended_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "prof.doc.signed_highrisk",
        "type": "profile",
        "pack_id": "pack.10",
        "name": "High-Risk Signed Document Profile",
        "description": "Process high-risk documents with mandatory signing, audit, and isolation.",
        "tags": ["docs", "signing", "security"],
        "controls_required": [
            "ctrl.obs.audit_log_append_only",
            "ctrl.sandbox.secrets_denied_by_default",
            "ctrl.obs.flight_recorder_bundle",
        ],
        "recommended_for_risk_tiers": ["high", "critical"],
    },
    {
        "id": "prof.doc.restricted_redaction",
        "type": "profile",
        "pack_id": "pack.10",
        "name": "Restricted Redaction Document Profile",
        "description": "Process documents with restricted data requiring redaction before sharing.",
        "tags": ["docs", "redaction", "compliance"],
        "controls_required": [
            "ctrl.obs.audit_log_append_only",
            "ctrl.sandbox.workspace_mounts_only",
            "ctrl.obs.structured_logging",
        ],
        "recommended_for_risk_tiers": ["high", "critical"],
    },
]
