"""Pack source — pack_08_streaming"""

ENTITIES = [
    {
        'id': 'cap.stream.consume',
        'type': 'capability',
        'name': 'Consume Stream',
        'description': 'Consume messages from a streaming topic with configurable delivery semantics (at-least-once, exactly-once).',
        'risk_tier': 'medium',
        'tags': [
            'streaming',
            'events',
            'consumer',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 1,
            'financial': 0,
            'time': 1,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
            'ctrl.obs.metrics-core',
        ],
        'idempotency': 'partial',
        'determinism': 'captured',
    },
    {
        'id': 'cap.stream.produce',
        'type': 'capability',
        'name': 'Produce to Stream',
        'description': 'Publish messages to a streaming topic with idempotency and ordering guarantees.',
        'risk_tier': 'medium',
        'tags': [
            'streaming',
            'events',
            'producer',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 2,
            'financial': 0,
            'time': 1,
            'reversibility': 'partially-reversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
            'ctrl.obs.tracing-distributed',
        ],
        'idempotency': 'partial',
        'determinism': 'captured',
    },
    {
        'id': 'cap.stream.replay',
        'type': 'capability',
        'name': 'Replay Stream',
        'description': 'Replay a stream from a specified offset or timestamp for reprocessing or recovery.',
        'risk_tier': 'high',
        'tags': [
            'streaming',
            'replay',
            'recovery',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 2,
            'network': 2,
            'financial': 1,
            'time': 3,
            'reversibility': 'partially-reversible',
        },
        'typical_controls': [
            'ctrl.obs.audit-log-append-only',
            'ctrl.obs.tracing-distributed',
        ],
        'idempotency': 'partial',
        'determinism': 'captured',
    },
    {
        'id': 'cap.projection.rebuild',
        'type': 'capability',
        'name': 'Rebuild Projection',
        'description': 'Rebuild a read-model projection by replaying events from source stream.',
        'risk_tier': 'medium',
        'tags': [
            'streaming',
            'cqrs',
            'projection',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 2,
            'network': 1,
            'financial': 0,
            'time': 3,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
            'ctrl.obs.metrics-core',
        ],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
]
