"""Pack source — pack_16_provenance"""

PACKS = [
    {
        'id': 'pack.16',
        'name': 'Provenance, Signing & Supply-Chain Integrity',
        'entity_count': 9,
    },
]

ENTITIES = [
    {
        'id': 'cap.prov.sign-artifact',
        'type': 'capability',
        'pack_id': 'pack.16',
        'name': 'Sign Artifact',
        'description': 'Apply a cryptographic signature to a build or data artifact using a managed key.',
        'risk_tier': 'critical',
        'tags': ['provenance', 'signing', 'supply-chain'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 0,
            'financial': 2,
            'time': 1,
            'reversibility': 'irreversible',
        },
        'typical_controls': ['ctrl.obs.audit-log-append-only', 'ctrl.sandbox.secrets-denied-by-default'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.prov.verify-signature',
        'type': 'capability',
        'pack_id': 'pack.16',
        'name': 'Verify Signature',
        'description': 'Verify the cryptographic signature of an artifact against known public keys.',
        'risk_tier': 'high',
        'tags': ['provenance', 'signing', 'supply-chain'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 0,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.obs.audit-log-append-only'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.prov.issue-attestation',
        'type': 'capability',
        'pack_id': 'pack.16',
        'name': 'Issue Attestation',
        'description': 'Issue a signed attestation statement (e.g., SLSA provenance, SBOM attestation).',
        'risk_tier': 'critical',
        'tags': ['provenance', 'attestation', 'supply-chain'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 0,
            'financial': 2,
            'time': 1,
            'reversibility': 'irreversible',
        },
        'typical_controls': ['ctrl.obs.audit-log-append-only', 'ctrl.sandbox.secrets-denied-by-default'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.prov.verify-attestation',
        'type': 'capability',
        'pack_id': 'pack.16',
        'name': 'Verify Attestation',
        'description': 'Verify a signed attestation statement before trusting an artifact.',
        'risk_tier': 'high',
        'tags': ['provenance', 'attestation', 'supply-chain'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 0,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.obs.audit-log-append-only'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.prov.generate-provenance-chain',
        'type': 'capability',
        'pack_id': 'pack.16',
        'name': 'Generate Provenance Chain',
        'description': 'Assemble complete provenance chain: source → build → scan → SBOM → signatures.',
        'risk_tier': 'high',
        'tags': ['provenance', 'supply-chain', 'audit'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 1,
            'financial': 0,
            'time': 2,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.obs.structured-logging', 'ctrl.obs.run-metadata-store'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'wrk.prov.signer',
        'type': 'worker_species',
        'pack_id': 'pack.16',
        'name': 'Provenance Signer Worker',
        'description': 'Sign build artifacts; emit signature and provenance metadata.',
        'risk_tier': 'critical',
        'level': 'L6',
        'guarantee': 'exactly-once',
        'determinism': 'deterministic',
        'blast_score': None,
        'required_controls': ['ctrl.obs.audit-log-append-only'],
        'handles_capabilities': ['cap.prov.sign_artifact'],
        'tags': ['provenance', 'signing'],
        'serves_capabilities': ['cap.prov.sign-artifact', 'cap.prov.issue-attestation'],
        'blast_radius_hint': {
            'data': 1,
            'network': 0,
            'financial': 2,
            'time': 1,
            'reversibility': 'irreversible',
        },
        'idempotency': 'full',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'wrk.prov.verifier',
        'type': 'worker_species',
        'pack_id': 'pack.16',
        'name': 'Provenance Verifier Worker',
        'description': 'Verify signatures and attestations; enforce fail-closed semantics.',
        'risk_tier': 'high',
        'level': 'L6',
        'guarantee': 'at-least-once',
        'determinism': 'deterministic',
        'blast_score': None,
        'required_controls': ['ctrl.obs.audit-log-append-only'],
        'handles_capabilities': ['cap.prov.verify_signature', 'cap.prov.verify_attestation'],
        'tags': ['provenance', 'signing'],
        'serves_capabilities': ['cap.prov.verify-signature', 'cap.prov.verify-attestation'],
        'blast_radius_hint': {
            'data': 0,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'idempotency': 'full',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'wrk.prov.provenance-assembler',
        'type': 'worker_species',
        'pack_id': 'pack.16',
        'name': 'Provenance Assembler Worker',
        'description': 'Assemble provenance chain (source, build, scan, SBOM, signatures).',
        'risk_tier': 'high',
        'level': 'L5',
        'guarantee': 'at-least-once',
        'determinism': 'deterministic',
        'blast_score': None,
        'required_controls': ['ctrl.obs.structured-logging'],
        'handles_capabilities': ['cap.prov.generate_provenance_chain'],
        'tags': ['provenance', 'supply-chain'],
        'serves_capabilities': ['cap.prov.generate-provenance-chain'],
        'blast_radius_hint': {
            'data': 1,
            'network': 1,
            'financial': 0,
            'time': 2,
            'reversibility': 'reversible',
        },
        'idempotency': 'full',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.prov.prod-strict',
        'type': 'profile',
        'pack_id': 'pack.16',
        'name': 'Production Strict Provenance Profile',
        'description': 'Strict production provenance posture: mandatory signing, attestation, and full provenance chain.',
        'tags': ['provenance', 'production', 'supply-chain'],
        'controls_required': ['ctrl.obs.audit-log-append-only', 'ctrl.obs.structured-logging', 'ctrl.sandbox.secrets-denied-by-default'],
        'recommended_for_risk_tiers': ['high', 'critical'],
        'wcp_namespace': 'reserved',
    },
]
