"""Pack 01: Sandboxing & Containment"""

PACKS = [
    {
        "id": "pack.01",
        "name": "Sandboxing & Containment",
        "entity_count": 19,
    },
]

ENTITIES = [
    # --- Capabilities ---
    {
        "id": "cap.mount.workspace",
        "type": "capability",
        "pack_id": "pack.01",
        "name": "Mount Workspace",
        "description": "Mount a dedicated workspace directory into the execution environment.",
        "risk_tier": "medium",
        "tags": ["sandbox", "filesystem"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 0, "financial": 0, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.sandbox.workspace_mounts_only", "ctrl.sandbox.readonly_rootfs"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.net.egress.allowlisted",
        "type": "capability",
        "pack_id": "pack.01",
        "name": "Network Egress (Allowlisted)",
        "description": "Outbound network access limited to allowlisted destinations via controlled proxy.",
        "risk_tier": "high",
        "tags": ["sandbox", "egress", "network"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 2, "network": 3, "financial": 1, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.sandbox.no_egress_default_deny", "ctrl.sandbox.path_allowlists"],
        "idempotency": "partial",
        "determinism": "non-deterministic",
    },
    {
        "id": "cap.net.egress.denied",
        "type": "capability",
        "pack_id": "pack.01",
        "name": "Network Egress Denied",
        "description": "Outbound network access disabled (default deny).",
        "risk_tier": "low",
        "tags": ["sandbox", "network"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.sandbox.no_egress_default_deny"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.fs.readonly",
        "type": "capability",
        "pack_id": "pack.01",
        "name": "Filesystem Read-Only",
        "description": "Execution environment filesystem is read-only except for mounted workspace.",
        "risk_tier": "low",
        "tags": ["sandbox", "filesystem"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.sandbox.readonly_rootfs"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.fs.workspace.write",
        "type": "capability",
        "pack_id": "pack.01",
        "name": "Workspace Write",
        "description": "Write and modify files only within the mounted workspace boundary.",
        "risk_tier": "medium",
        "tags": ["sandbox", "filesystem"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 2, "network": 0, "financial": 0, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.sandbox.workspace_mounts_only", "ctrl.sandbox.path_allowlists"],
        "idempotency": "partial",
        "determinism": "deterministic",
    },
    {
        "id": "cap.exec.container",
        "type": "capability",
        "pack_id": "pack.01",
        "name": "Execute in Container",
        "description": "Execute artifact within a container boundary with restricted privileges.",
        "risk_tier": "medium",
        "tags": ["sandbox", "execution"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 0, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.sandbox.no_privileged_containers", "ctrl.sandbox.resource_limits_strict", "ctrl.sandbox.syscall_filtering"],
        "idempotency": "partial",
        "determinism": "captured",
    },
    {
        "id": "cap.exec.vm",
        "type": "capability",
        "pack_id": "pack.01",
        "name": "Execute in VM",
        "description": "Execute artifact within a VM boundary (stronger isolation than containers).",
        "risk_tier": "medium",
        "tags": ["sandbox", "execution"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 0, "time": 2, "reversibility": "reversible"},
        "typical_controls": ["ctrl.sandbox.resource_limits_strict", "ctrl.sandbox.no_egress_default_deny"],
        "idempotency": "partial",
        "determinism": "captured",
    },
    # --- Controls ---
    {
        "id": "ctrl.sandbox.no_egress_default_deny",
        "type": "control",
        "pack_id": "pack.01",
        "name": "No Egress Default Deny",
        "description": "Disable all outbound network by default; egress requires explicit allowlist.",
        "tags": ["sandbox", "network", "safety"],
        "enforcement_point": "platform",
        "required_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "ctrl.sandbox.readonly_rootfs",
        "type": "control",
        "pack_id": "pack.01",
        "name": "Read-Only Root Filesystem",
        "description": "Root filesystem is read-only; only workspace mount is writable.",
        "tags": ["sandbox", "filesystem"],
        "enforcement_point": "platform",
        "required_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "ctrl.sandbox.workspace_mounts_only",
        "type": "control",
        "pack_id": "pack.01",
        "name": "Workspace Mounts Only",
        "description": "Only workspace path may be mounted; all other mounts denied.",
        "tags": ["sandbox", "filesystem"],
        "enforcement_point": "platform",
        "required_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "ctrl.sandbox.resource_limits_strict",
        "type": "control",
        "pack_id": "pack.01",
        "name": "Strict Resource Limits",
        "description": "Enforce CPU, RAM, and time limits on worker execution.",
        "tags": ["sandbox", "reliability"],
        "enforcement_point": "platform",
        "required_for_risk_tiers": ["low", "medium", "high", "critical"],
    },
    {
        "id": "ctrl.sandbox.syscall_filtering",
        "type": "control",
        "pack_id": "pack.01",
        "name": "Syscall Filtering",
        "description": "Apply seccomp/AppArmor profiles to restrict permitted system calls.",
        "tags": ["sandbox", "security"],
        "enforcement_point": "platform",
        "required_for_risk_tiers": ["high", "critical"],
    },
    {
        "id": "ctrl.sandbox.no_privileged_containers",
        "type": "control",
        "pack_id": "pack.01",
        "name": "No Privileged Containers",
        "description": "Container execution must not use privileged mode.",
        "tags": ["sandbox", "security"],
        "enforcement_point": "platform",
        "required_for_risk_tiers": ["low", "medium", "high", "critical"],
    },
    {
        "id": "ctrl.sandbox.secrets_denied_by_default",
        "type": "control",
        "pack_id": "pack.01",
        "name": "Secrets Denied by Default",
        "description": "No secrets injected into workers unless explicitly granted.",
        "tags": ["sandbox", "secrets", "safety"],
        "enforcement_point": "platform",
        "required_for_risk_tiers": ["low", "medium", "high", "critical"],
    },
    {
        "id": "ctrl.sandbox.flight_recorder",
        "type": "control",
        "pack_id": "pack.01",
        "name": "Flight Recorder",
        "description": "Record all tool calls and file activity for audit purposes.",
        "tags": ["sandbox", "observability", "audit"],
        "enforcement_point": "worker",
        "required_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "ctrl.sandbox.path_allowlists",
        "type": "control",
        "pack_id": "pack.01",
        "name": "Path Allowlists",
        "description": "Deny access to sensitive filesystem paths not in the allowlist.",
        "tags": ["sandbox", "filesystem", "security"],
        "enforcement_point": "platform",
        "required_for_risk_tiers": ["medium", "high", "critical"],
    },
    # --- Profiles ---
    {
        "id": "prof.sandbox.no_egress",
        "type": "profile",
        "pack_id": "pack.01",
        "name": "No-Egress Sandbox Profile",
        "description": "No-egress sandbox posture: all outbound network disabled, workspace-only writes.",
        "tags": ["sandbox", "network"],
        "controls_required": [
            "ctrl.sandbox.no_egress_default_deny",
            "ctrl.sandbox.workspace_mounts_only",
            "ctrl.sandbox.readonly_rootfs",
            "ctrl.sandbox.secrets_denied_by_default",
        ],
        "recommended_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "prof.sandbox.vm_strict",
        "type": "profile",
        "pack_id": "pack.01",
        "name": "VM-Strict Sandbox Profile",
        "description": "VM-isolated strict sandbox posture: full VM isolation, no privileged access.",
        "tags": ["sandbox", "security"],
        "controls_required": [
            "ctrl.sandbox.no_egress_default_deny",
            "ctrl.sandbox.resource_limits_strict",
            "ctrl.sandbox.secrets_denied_by_default",
            "ctrl.sandbox.flight_recorder",
        ],
        "recommended_for_risk_tiers": ["high", "critical"],
    },
    {
        "id": "prof.sandbox.allowlisted_egress",
        "type": "profile",
        "pack_id": "pack.01",
        "name": "Allowlisted Egress Sandbox Profile",
        "description": "Sandbox posture allowing egress only to explicitly allowlisted destinations.",
        "tags": ["sandbox", "network", "egress"],
        "controls_required": [
            "ctrl.sandbox.path_allowlists",
            "ctrl.sandbox.workspace_mounts_only",
            "ctrl.sandbox.no_privileged_containers",
            "ctrl.sandbox.flight_recorder",
        ],
        "recommended_for_risk_tiers": ["medium", "high"],
    },
]
