"""Pack 18: Multi-Org / Federated Trust"""

PACKS = [
    {
        "id": "pack.18",
        "name": "Multi-Org / Federated Trust",
        "entity_count": 8,
    },
]

ENTITIES = [
    # --- Capabilities ---
    {
        "id": "cap.fed.accept_external_identity",
        "type": "capability",
        "pack_id": "pack.18",
        "name": "Accept External Identity",
        "description": "Accept and validate an identity token from a trusted external organization.",
        "risk_tier": "high",
        "tags": ["federation", "identity", "multi-org"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 2, "network": 2, "financial": 1, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only", "ctrl.obs.structured_logging"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.fed.exchange_tokens",
        "type": "capability",
        "pack_id": "pack.18",
        "name": "Exchange Federation Tokens",
        "description": "Exchange a partner token for a scoped local token via federation handshake.",
        "risk_tier": "high",
        "tags": ["federation", "tokens", "identity"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 2, "financial": 1, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only"],
        "idempotency": "partial",
        "determinism": "deterministic",
    },
    {
        "id": "cap.fed.enforce_data_contract",
        "type": "capability",
        "pack_id": "pack.18",
        "name": "Enforce Data Contract",
        "description": "Validate inbound/outbound data against the partner data contract before processing.",
        "risk_tier": "high",
        "tags": ["federation", "contracts", "data-governance"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 2, "network": 1, "financial": 1, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only", "ctrl.obs.structured_logging"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.fed.isolate_guest_workers",
        "type": "capability",
        "pack_id": "pack.18",
        "name": "Isolate Guest Workers",
        "description": "Run partner/guest workers in isolated execution pools with default-deny capabilities.",
        "risk_tier": "high",
        "tags": ["federation", "sandbox", "isolation"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 2, "network": 1, "financial": 1, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.sandbox.no_egress_default_deny", "ctrl.sandbox.workspace_mounts_only"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    # --- Worker Species ---
    {
        "id": "wrk.fed.gateway",
        "type": "worker_species",
        "pack_id": "pack.18",
        "name": "Federation Gateway Worker",
        "description": "Front-door for partner integrations; validate identity; issue scoped tokens.",
        "risk_tier": "high",
        "level": "L5",
        "guarantee": "at-least-once",
        "determinism": "deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.audit_log_append_only",
            "ctrl.obs.structured_logging",
        ],
        "handles_capabilities": [
            "cap.fed.accept_external_identity",
            "cap.fed.exchange_tokens",
        ],
        "tags": ["federation", "identity"],
        "serves_capabilities": ["cap.fed.accept_external_identity", "cap.fed.exchange_tokens", "cap.fed.enforce_data_contract"],
        "blast_radius_hint": {"data": 2, "network": 2, "financial": 1, "time": 1, "reversibility": "reversible"},
        "idempotency": "partial",
    },
    {
        "id": "wrk.fed.guest_pool.worker",
        "type": "worker_species",
        "pack_id": "pack.18",
        "name": "Guest Pool Worker",
        "description": "Execute partner workloads in isolated pools with default-deny capabilities.",
        "risk_tier": "high",
        "level": "L4",
        "guarantee": "best-effort",
        "determinism": "nondeterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.sandbox.no_egress_default_deny",
            "ctrl.sandbox.workspace_mounts_only",
        ],
        "handles_capabilities": ["cap.fed.isolate_guest_workers"],
        "tags": ["federation", "sandbox"],
        "serves_capabilities": ["cap.fed.isolate_guest_workers"],
        "blast_radius_hint": {"data": 2, "network": 0, "financial": 1, "time": 1, "reversibility": "reversible"},
        "idempotency": "partial",
    },
    # --- Profiles ---
    {
        "id": "prof.fed.partner_strict",
        "type": "profile",
        "pack_id": "pack.18",
        "name": "Strict Partner Federation Profile",
        "description": "Strict federation posture: validated identity, scoped tokens, data contract enforcement, full audit.",
        "tags": ["federation", "partner", "security"],
        "controls_required": [
            "ctrl.obs.audit_log_append_only",
            "ctrl.obs.structured_logging",
            "ctrl.sandbox.no_egress_default_deny",
        ],
        "recommended_for_risk_tiers": ["high", "critical"],
    },
    {
        "id": "prof.fed.guest_isolated",
        "type": "profile",
        "pack_id": "pack.18",
        "name": "Guest Isolated Federation Profile",
        "description": "Guest workload isolation posture: sandboxed execution, no egress, workspace-only access.",
        "tags": ["federation", "sandbox", "isolation"],
        "controls_required": [
            "ctrl.sandbox.no_egress_default_deny",
            "ctrl.sandbox.workspace_mounts_only",
            "ctrl.sandbox.resource_limits_strict",
        ],
        "recommended_for_risk_tiers": ["medium", "high", "critical"],
    },
]
