"""Pack source — pack_03_observability"""

ENTITIES = [
    {
        'id': 'cap.side-effect.write-external',
        'type': 'capability',
        'name': 'Write External Side Effect',
        'description': 'Perform a write to an external system (database, API, filesystem) as a declared side effect.',
        'risk_tier': 'high',
        'tags': [
            'side-effects',
            'observability',
            'audit',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 3,
            'network': 2,
            'financial': 1,
            'time': 2,
            'reversibility': 'partially-reversible',
        },
        'typical_controls': [
            'ctrl.obs.audit-log-append-only',
            'ctrl.obs.structured-logging',
        ],
        'idempotency': 'partial',
        'determinism': 'captured',
    },
    {
        'id': 'cap.ledger.write',
        'type': 'capability',
        'name': 'Write Audit Ledger',
        'description': 'Append an immutable entry to the audit ledger.',
        'risk_tier': 'high',
        'tags': [
            'audit',
            'ledger',
            'integrity',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'irreversible',
        },
        'typical_controls': [
            'ctrl.obs.audit-log-append-only',
        ],
        'idempotency': 'partial',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.outbox.publish',
        'type': 'capability',
        'name': 'Publish via Outbox',
        'description': 'Publish a message via transactional outbox pattern ensuring at-least-once delivery.',
        'risk_tier': 'medium',
        'tags': [
            'outbox',
            'messaging',
            'reliability',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 2,
            'financial': 0,
            'time': 1,
            'reversibility': 'partially-reversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
            'ctrl.obs.run-metadata-store',
        ],
        'idempotency': 'partial',
        'determinism': 'captured',
    },
    {
        'id': 'cap.inbox.dedup',
        'type': 'capability',
        'name': 'Inbox Deduplication',
        'description': 'Deduplicate incoming messages using idempotency keys before processing.',
        'risk_tier': 'low',
        'tags': [
            'inbox',
            'dedup',
            'reliability',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 0,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
        ],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'ctrl.obs.structured-logging',
        'type': 'control',
        'name': 'Structured Logging',
        'description': 'All worker output must use structured (JSON) logging with correlation_id and tenant_id.',
        'tags': [
            'observability',
            'logging',
        ],
        'enforcement_point': 'worker',
        'required_for_risk_tiers': [
            'low',
            'medium',
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.obs.metrics-core',
        'type': 'control',
        'name': 'Core Metrics',
        'description': 'Workers must emit core metrics (latency, error rate, throughput).',
        'tags': [
            'observability',
            'metrics',
        ],
        'enforcement_point': 'worker',
        'required_for_risk_tiers': [
            'medium',
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.obs.tracing-distributed',
        'type': 'control',
        'name': 'Distributed Tracing',
        'description': 'Workers must emit distributed trace spans with correlation_id propagation.',
        'tags': [
            'observability',
            'tracing',
        ],
        'enforcement_point': 'worker',
        'required_for_risk_tiers': [
            'medium',
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.obs.audit-log-append-only',
        'type': 'control',
        'name': 'Append-Only Audit Log',
        'description': 'Audit entries must be written to an append-only log; modifications forbidden.',
        'tags': [
            'observability',
            'audit',
            'integrity',
        ],
        'enforcement_point': 'platform',
        'required_for_risk_tiers': [
            'medium',
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.obs.run-metadata-store',
        'type': 'control',
        'name': 'Run Metadata Store',
        'description': 'Store run metadata (inputs, outputs, timing, worker version) per execution.',
        'tags': [
            'observability',
            'provenance',
        ],
        'enforcement_point': 'worker',
        'required_for_risk_tiers': [
            'medium',
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.obs.slo-alerting',
        'type': 'control',
        'name': 'SLO Alerting',
        'description': 'Alert when SLO thresholds are breached (error budget, latency p99).',
        'tags': [
            'observability',
            'slo',
            'reliability',
        ],
        'enforcement_point': 'platform',
        'required_for_risk_tiers': [
            'medium',
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.obs.flight-recorder-bundle',
        'type': 'control',
        'name': 'Flight Recorder Bundle',
        'description': 'Collect and retain full flight recorder bundle (all events, tool calls, inputs/outputs) for forensic replay.',
        'tags': [
            'observability',
            'audit',
            'forensics',
        ],
        'enforcement_point': 'worker',
        'required_for_risk_tiers': [
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
]
