"""Pack 26: Workforce OS (Meta-Worker: Composition, Routing, Governance)"""

PACKS = [
    {
        "id": "pack.26",
        "name": "Workforce OS (Meta-Worker: Composition, Routing, Governance)",
        "entity_count": 20,
    },
]

ENTITIES = [
    # --- Capabilities ---
    {
        "id": "cap.os.register_worker",
        "type": "capability",
        "pack_id": "pack.26",
        "name": "Register Worker",
        "description": "Enroll a worker into the workforce registry with validated controls and provenance.",
        "risk_tier": "high",
        "tags": ["workforce-os", "registry", "governance"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.os.worker_registry", "ctrl.obs.audit_log_append_only"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.os.route_task",
        "type": "capability",
        "pack_id": "pack.26",
        "name": "Route Task",
        "description": "Route a task to the appropriate worker using deterministic routing rules.",
        "risk_tier": "high",
        "tags": ["workforce-os", "routing", "orchestration"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 1, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.os.routing_rules", "ctrl.os.policy_gate_every_step"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.os.compose_workflow",
        "type": "capability",
        "pack_id": "pack.26",
        "name": "Compose Workflow",
        "description": "Compose multi-worker workflows with policy gates, cost controls, and provenance.",
        "risk_tier": "high",
        "tags": ["workforce-os", "composition", "orchestration"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 2, "network": 2, "financial": 2, "time": 2, "reversibility": "partially-reversible"},
        "typical_controls": ["ctrl.os.routing_rules", "ctrl.os.end_to_end_correlation"],
        "idempotency": "partial",
        "determinism": "captured",
    },
    {
        "id": "cap.os.enforce_policies",
        "type": "capability",
        "pack_id": "pack.26",
        "name": "Enforce Policies",
        "description": "Enforce workforce-wide policies (budget, data label, QoS, privileges) at every routing step.",
        "risk_tier": "critical",
        "tags": ["workforce-os", "policy", "governance"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 2, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.os.policy_gate_every_step", "ctrl.pol.default_deny"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.os.observe_end_to_end",
        "type": "capability",
        "pack_id": "pack.26",
        "name": "Observe End-to-End",
        "description": "Collect end-to-end telemetry with correlation_id across all workers in a request.",
        "risk_tier": "medium",
        "tags": ["workforce-os", "observability", "tracing"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.os.end_to_end_correlation", "ctrl.obs.tracing_distributed"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.os.emergency_controls",
        "type": "capability",
        "pack_id": "pack.26",
        "name": "Emergency Controls",
        "description": "Activate global or per-worker kill switches for emergency shutdown or quarantine.",
        "risk_tier": "critical",
        "tags": ["workforce-os", "emergency", "safety"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 4, "financial": 3, "time": 3, "reversibility": "reversible"},
        "typical_controls": ["ctrl.os.global_kill_switches", "ctrl.obs.audit_log_append_only"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.os.govern_worker_lifecycle",
        "type": "capability",
        "pack_id": "pack.26",
        "name": "Govern Worker Lifecycle",
        "description": "Manage worker enrollment, suspension, retirement, and version transitions.",
        "risk_tier": "high",
        "tags": ["workforce-os", "lifecycle", "governance"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 1, "time": 2, "reversibility": "reversible"},
        "typical_controls": ["ctrl.os.worker_registry", "ctrl.obs.audit_log_append_only"],
        "idempotency": "partial",
        "determinism": "deterministic",
    },
    {
        "id": "cap.os.memory_and_context_service",
        "type": "capability",
        "pack_id": "pack.26",
        "name": "Memory and Context Service",
        "description": "Provide memory and context services to workers (scoped retrieval, embedding, summarization).",
        "risk_tier": "medium",
        "tags": ["workforce-os", "memory", "context"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 1, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging", "ctrl.cost.monthly_token_budget"],
        "idempotency": "partial",
        "determinism": "non-deterministic",
    },
    # --- Worker Species ---
    {
        "id": "wrk.os.workforce_router",
        "type": "worker_species",
        "pack_id": "pack.26",
        "name": "Workforce Router Worker",
        "description": "Route, compose, and govern across all workers; enforce policies, budgets, QoS, and provenance.",
        "risk_tier": "critical",
        "level": "L8",
        "guarantee": "exactly-once",
        "determinism": "deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.os.worker_registry",
            "ctrl.os.routing_rules",
            "ctrl.os.policy_gate_every_step",
            "ctrl.os.end_to_end_correlation",
            "ctrl.os.global_kill_switches",
        ],
        "handles_capabilities": [
            "cap.os.route_task",
            "cap.os.compose_workflow",
            "cap.os.enforce_policies",
        ],
        "tags": ["workforce-os", "routing", "governance"],
        "serves_capabilities": ["cap.os.route_task", "cap.os.compose_workflow", "cap.os.enforce_policies"],
        "blast_radius_hint": {"data": 2, "network": 4, "financial": 3, "time": 3, "reversibility": "partially-reversible"},
        "idempotency": "full",
    },
    {
        "id": "wrk.os.registry_manager",
        "type": "worker_species",
        "pack_id": "pack.26",
        "name": "Registry Manager Worker",
        "description": "Maintain worker registry; enroll/retire; validate controls and provenance.",
        "risk_tier": "high",
        "level": "L6",
        "guarantee": "exactly-once",
        "determinism": "deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.os.worker_registry",
            "ctrl.obs.audit_log_append_only",
        ],
        "handles_capabilities": [
            "cap.os.register_worker",
            "cap.os.govern_worker_lifecycle",
        ],
        "tags": ["workforce-os", "registry"],
        "serves_capabilities": ["cap.os.register_worker", "cap.os.govern_worker_lifecycle"],
        "blast_radius_hint": {"data": 1, "network": 0, "financial": 0, "time": 1, "reversibility": "reversible"},
        "idempotency": "full",
    },
    {
        "id": "wrk.os.incident_commander",
        "type": "worker_species",
        "pack_id": "pack.26",
        "name": "Incident Commander Worker",
        "description": "Coordinate incident mode: kill switches, quarantine, runbooks, evidence bundles.",
        "risk_tier": "critical",
        "level": "L7",
        "guarantee": "at-least-once",
        "determinism": "nondeterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.os.global_kill_switches",
            "ctrl.obs.audit_log_append_only",
        ],
        "handles_capabilities": ["cap.os.emergency_controls"],
        "tags": ["workforce-os", "incident", "emergency"],
        "serves_capabilities": ["cap.os.emergency_controls"],
        "blast_radius_hint": {"data": 0, "network": 4, "financial": 3, "time": 3, "reversibility": "reversible"},
        "idempotency": "full",
    },
    # --- Controls ---
    {
        "id": "ctrl.os.worker_registry",
        "type": "control",
        "pack_id": "pack.26",
        "name": "Worker Registry",
        "description": "Maintain an enrolled worker registry; deny execution for unregistered workers.",
        "tags": ["workforce-os", "registry", "governance"],
        "enforcement_point": "hall",
        "required_for_risk_tiers": ["low", "medium", "high", "critical"],
    },
    {
        "id": "ctrl.os.routing_rules",
        "type": "control",
        "pack_id": "pack.26",
        "name": "Deterministic Routing Rules",
        "description": "Enforce deterministic, versioned routing rules (first-match-wins).",
        "tags": ["workforce-os", "routing"],
        "enforcement_point": "hall",
        "required_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "ctrl.os.policy_gate_every_step",
        "type": "control",
        "pack_id": "pack.26",
        "name": "Policy Gate Every Step",
        "description": "Apply policy gate at every routing step, not just pre-run.",
        "tags": ["workforce-os", "policy", "governance"],
        "enforcement_point": "hall",
        "required_for_risk_tiers": ["high", "critical"],
    },
    {
        "id": "ctrl.os.end_to_end_correlation",
        "type": "control",
        "pack_id": "pack.26",
        "name": "End-to-End Correlation",
        "description": "Propagate correlation_id across every worker call, tool call, and telemetry event.",
        "tags": ["workforce-os", "observability", "tracing"],
        "enforcement_point": "worker",
        "required_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "ctrl.os.global_kill_switches",
        "type": "control",
        "pack_id": "pack.26",
        "name": "Global Kill Switches",
        "description": "Global and per-worker kill switches for emergency shutdown.",
        "tags": ["workforce-os", "emergency", "safety"],
        "enforcement_point": "platform",
        "required_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "ctrl.os.budget_and_cost_enforcement",
        "type": "control",
        "pack_id": "pack.26",
        "name": "Budget and Cost Enforcement",
        "description": "Enforce per-agent, per-tenant cost caps and budgets.",
        "tags": ["workforce-os", "cost", "governance"],
        "enforcement_point": "hall",
        "required_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "ctrl.os.provenance_requirements",
        "type": "control",
        "pack_id": "pack.26",
        "name": "Provenance Requirements",
        "description": "Require signed provenance for all production worker executions.",
        "tags": ["workforce-os", "provenance", "supply-chain"],
        "enforcement_point": "hall",
        "required_for_risk_tiers": ["high", "critical"],
    },
    # --- Profiles ---
    {
        "id": "prof.os.production_control_plane",
        "type": "profile",
        "pack_id": "pack.26",
        "name": "Production Control Plane Profile",
        "description": "Production workforce OS posture: registry, routing, policy gates, cost enforcement, provenance.",
        "tags": ["workforce-os", "production", "governance"],
        "controls_required": [
            "ctrl.os.worker_registry",
            "ctrl.os.routing_rules",
            "ctrl.os.policy_gate_every_step",
            "ctrl.os.end_to_end_correlation",
            "ctrl.os.budget_and_cost_enforcement",
            "ctrl.os.provenance_requirements",
        ],
        "recommended_for_risk_tiers": ["high", "critical"],
    },
    {
        "id": "prof.os.incident_mode",
        "type": "profile",
        "pack_id": "pack.26",
        "name": "OS Incident Mode Profile",
        "description": "Incident mode workforce OS posture: kill switches active, forensic logging, restricted routing.",
        "tags": ["workforce-os", "incident", "emergency"],
        "controls_required": [
            "ctrl.os.global_kill_switches",
            "ctrl.obs.audit_log_append_only",
            "ctrl.obs.flight_recorder_bundle",
        ],
        "recommended_for_risk_tiers": ["high", "critical"],
    },
]
