"""Pack 23: Integration Adapters (3rd-Party APIs, Webhooks, Contracts)"""

PACKS = [
    {
        "id": "pack.23",
        "name": "Integration Adapters (3rd-Party APIs, Webhooks, Contracts)",
        "entity_count": 9,
    },
]

ENTITIES = [
    # --- Capabilities ---
    {
        "id": "cap.int.webhook.verify",
        "type": "capability",
        "pack_id": "pack.23",
        "name": "Verify Inbound Webhook",
        "description": "Verify the signature and authenticity of an inbound webhook before processing.",
        "risk_tier": "medium",
        "tags": ["integrations", "webhooks", "security"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 1, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.int.api.call",
        "type": "capability",
        "pack_id": "pack.23",
        "name": "Call External API",
        "description": "Call a third-party API with backoff, circuit breakers, and rate limiting.",
        "risk_tier": "medium",
        "tags": ["integrations", "egress", "resilience"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 3, "financial": 2, "time": 1, "reversibility": "partially-reversible"},
        "typical_controls": ["ctrl.obs.structured_logging", "ctrl.obs.metrics_core"],
        "idempotency": "partial",
        "determinism": "non-deterministic",
    },
    {
        "id": "cap.int.contract.validate",
        "type": "capability",
        "pack_id": "pack.23",
        "name": "Validate Data Contract",
        "description": "Validate a data payload against a versioned data contract schema.",
        "risk_tier": "medium",
        "tags": ["integrations", "contracts", "validation"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.int.replay_webhook",
        "type": "capability",
        "pack_id": "pack.23",
        "name": "Replay Webhook",
        "description": "Replay a previously received webhook event for recovery or re-processing.",
        "risk_tier": "medium",
        "tags": ["integrations", "webhooks", "replay"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 1, "time": 1, "reversibility": "partially-reversible"},
        "typical_controls": ["ctrl.obs.structured_logging", "ctrl.obs.audit_log_append_only"],
        "idempotency": "partial",
        "determinism": "captured",
    },
    {
        "id": "cap.int.rotate_credentials",
        "type": "capability",
        "pack_id": "pack.23",
        "name": "Rotate Integration Credentials",
        "description": "Rotate API keys, OAuth tokens, or other credentials for a third-party integration.",
        "risk_tier": "high",
        "tags": ["integrations", "credentials", "rotation"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 2, "financial": 2, "time": 2, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only", "ctrl.sandbox.secrets_denied_by_default"],
        "idempotency": "partial",
        "determinism": "deterministic",
    },
    # --- Worker Species ---
    {
        "id": "wrk.int.webhook_ingest",
        "type": "worker_species",
        "pack_id": "pack.23",
        "name": "Webhook Ingest Worker",
        "description": "Ingest external webhooks; verify signatures; validate contracts; enqueue.",
        "risk_tier": "medium",
        "level": "L4",
        "guarantee": "at-least-once",
        "determinism": "deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.structured_logging",
        ],
        "handles_capabilities": [
            "cap.int.webhook.verify",
            "cap.int.replay_webhook",
        ],
        "tags": ["integrations", "webhooks"],
        "serves_capabilities": ["cap.int.webhook.verify", "cap.int.replay_webhook", "cap.int.contract.validate"],
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 0, "time": 0, "reversibility": "reversible"},
        "idempotency": "full",
    },
    {
        "id": "wrk.int.api_adapter",
        "type": "worker_species",
        "pack_id": "pack.23",
        "name": "API Adapter Worker",
        "description": "Call external APIs with backoff, circuit breakers, rate limits, and idempotency.",
        "risk_tier": "medium",
        "level": "L4",
        "guarantee": "at-least-once",
        "determinism": "captured-deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.structured_logging",
            "ctrl.obs.metrics_core",
        ],
        "handles_capabilities": ["cap.int.api.call"],
        "tags": ["integrations", "egress", "resilience"],
        "serves_capabilities": ["cap.int.api.call"],
        "blast_radius_hint": {"data": 1, "network": 3, "financial": 2, "time": 1, "reversibility": "partially-reversible"},
        "idempotency": "partial",
    },
    # --- Profiles ---
    {
        "id": "prof.int.webhook_strict",
        "type": "profile",
        "pack_id": "pack.23",
        "name": "Strict Webhook Integration Profile",
        "description": "Strict webhook posture: signature verification, contract validation, replay idempotency.",
        "tags": ["integrations", "webhooks", "strict"],
        "controls_required": [
            "ctrl.obs.structured_logging",
            "ctrl.obs.audit_log_append_only",
        ],
        "recommended_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "prof.int.resilient_adapter",
        "type": "profile",
        "pack_id": "pack.23",
        "name": "Resilient Adapter Integration Profile",
        "description": "Resilient API adapter posture: circuit breakers, backoff, rate limits, metrics.",
        "tags": ["integrations", "resilience", "egress"],
        "controls_required": [
            "ctrl.obs.metrics_core",
            "ctrl.obs.structured_logging",
        ],
        "recommended_for_risk_tiers": ["medium", "high"],
    },
]
