"""Pack source — pack_15_policy"""

ENTITIES = [
    {
        'id': 'cap.policy.evaluate',
        'type': 'capability',
        'name': 'Evaluate Policy',
        'description': 'Evaluate an action against loaded policy rules and return allow/deny with rationale.',
        'risk_tier': 'high',
        'tags': [
            'policy',
            'authorization',
            'governance',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 0,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.pol.policy-engine-runtime',
            'ctrl.pol.default-deny',
            'ctrl.pol.audit-policy-decisions',
        ],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.policy.update',
        'type': 'capability',
        'name': 'Update Policy',
        'description': 'Publish a new versioned policy to the policy engine for enforcement.',
        'risk_tier': 'high',
        'tags': [
            'policy',
            'governance',
            'change-control',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 1,
            'financial': 2,
            'time': 2,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.pol.policy-versioning',
            'ctrl.obs.audit-log-append-only',
        ],
        'idempotency': 'partial',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.policy.canary',
        'type': 'capability',
        'name': 'Canary Policy Rollout',
        'description': 'Activate a new policy version for a canary percentage of traffic before full rollout.',
        'risk_tier': 'high',
        'tags': [
            'policy',
            'canary',
            'governance',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 0,
            'network': 1,
            'financial': 2,
            'time': 2,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.pol.policy-versioning',
            'ctrl.obs.audit-log-append-only',
        ],
        'idempotency': 'partial',
        'determinism': 'deterministic',
    },
    {
        'id': 'wrk.pol.policy-gate',
        'type': 'worker_species',
        'name': 'Policy Gate Worker',
        'description': 'Evaluate actions against policy; emit allow/deny decisions and audit trail.',
        'risk_tier': 'high',
        'determinism': 'deterministic',
        'required_controls': [
            'ctrl.pol.policy-engine-runtime',
            'ctrl.pol.default-deny',
            'ctrl.pol.audit-policy-decisions',
            'ctrl.pol.policy-versioning',
        ],
        'tags': [
            'policy',
            'authorization',
            'governance',
        ],
        'serves_capabilities': [
            'cap.policy.evaluate',
        ],
        'blast_radius_hint': {
            'data': 0,
            'network': 0,
            'financial': 2,
            'time': 0,
            'reversibility': 'reversible',
        },
        'idempotency': 'full',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.pol.policy-engine-runtime',
        'type': 'control',
        'name': 'Policy Engine Runtime',
        'description': 'Policy engine must be running and reachable before any guarded action executes.',
        'tags': [
            'policy',
            'governance',
        ],
        'enforcement_point': 'platform',
        'required_for_risk_tiers': [
            'medium',
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.pol.default-deny',
        'type': 'control',
        'name': 'Default Deny',
        'description': 'Deny any capability not explicitly allowed by policy.',
        'tags': [
            'policy',
            'safety',
        ],
        'enforcement_point': 'hall',
        'required_for_risk_tiers': [
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.pol.audit-policy-decisions',
        'type': 'control',
        'name': 'Audit Policy Decisions',
        'description': 'Log every policy allow/deny decision to the append-only audit ledger.',
        'tags': [
            'policy',
            'audit',
            'observability',
        ],
        'enforcement_point': 'worker',
        'required_for_risk_tiers': [
            'medium',
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.pol.policy-versioning',
        'type': 'control',
        'name': 'Policy Versioning',
        'description': 'Policies must be versioned artifacts; unversioned policies cannot be enforced.',
        'tags': [
            'policy',
            'governance',
        ],
        'enforcement_point': 'hall',
        'required_for_risk_tiers': [
            'medium',
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.pol.default-deny-strict',
        'type': 'profile',
        'name': 'Strict Default Deny Policy Profile',
        'description': 'Strict policy posture: default-deny everything, versioned policies, full audit trail.',
        'tags': [
            'policy',
            'strict',
            'governance',
        ],
        'controls_required': [
            'ctrl.pol.policy-engine-runtime',
            'ctrl.pol.default-deny',
            'ctrl.pol.audit-policy-decisions',
            'ctrl.pol.policy-versioning',
        ],
        'recommended_for_risk_tiers': [
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
]
