"""Pack source — pack_01_sandboxing"""

PACKS = [
    {
        'id': 'pack.01',
        'name': 'Sandboxing & Containment',
        'entity_count': 19,
    },
]

ENTITIES = [
    {
        'id': 'cap.mount.workspace',
        'type': 'capability',
        'pack_id': 'pack.01',
        'name': 'Mount Workspace',
        'description': 'Mount a dedicated workspace directory into the execution environment.',
        'risk_tier': 'medium',
        'tags': ['sandbox', 'filesystem'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 0,
            'financial': 0,
            'time': 1,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.sandbox.workspace-mounts-only', 'ctrl.sandbox.readonly-rootfs'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.net.egress.allowlisted',
        'type': 'capability',
        'pack_id': 'pack.01',
        'name': 'Network Egress (Allowlisted)',
        'description': 'Outbound network access limited to allowlisted destinations via controlled proxy.',
        'risk_tier': 'high',
        'tags': ['sandbox', 'egress', 'network'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 2,
            'network': 3,
            'financial': 1,
            'time': 1,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.sandbox.no-egress-default-deny', 'ctrl.sandbox.path-allowlists'],
        'idempotency': 'partial',
        'determinism': 'non-deterministic',
    },
    {
        'id': 'cap.net.egress.denied',
        'type': 'capability',
        'pack_id': 'pack.01',
        'name': 'Network Egress Denied',
        'description': 'Outbound network access disabled (default deny).',
        'risk_tier': 'low',
        'tags': ['sandbox', 'network'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 0,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.sandbox.no-egress-default-deny'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.fs.readonly',
        'type': 'capability',
        'pack_id': 'pack.01',
        'name': 'Filesystem Read-Only',
        'description': 'Execution environment filesystem is read-only except for mounted workspace.',
        'risk_tier': 'low',
        'tags': ['sandbox', 'filesystem'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 0,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.sandbox.readonly-rootfs'],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.fs.workspace.write',
        'type': 'capability',
        'pack_id': 'pack.01',
        'name': 'Workspace Write',
        'description': 'Write and modify files only within the mounted workspace boundary.',
        'risk_tier': 'medium',
        'tags': ['sandbox', 'filesystem'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 2,
            'network': 0,
            'financial': 0,
            'time': 1,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.sandbox.workspace-mounts-only', 'ctrl.sandbox.path-allowlists'],
        'idempotency': 'partial',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.exec.container',
        'type': 'capability',
        'pack_id': 'pack.01',
        'name': 'Execute in Container',
        'description': 'Execute artifact within a container boundary with restricted privileges.',
        'risk_tier': 'medium',
        'tags': ['sandbox', 'execution'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 1,
            'financial': 0,
            'time': 1,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.sandbox.no-privileged-containers', 'ctrl.sandbox.resource-limits-strict', 'ctrl.sandbox.syscall-filtering'],
        'idempotency': 'partial',
        'determinism': 'captured',
    },
    {
        'id': 'cap.exec.vm',
        'type': 'capability',
        'pack_id': 'pack.01',
        'name': 'Execute in VM',
        'description': 'Execute artifact within a VM boundary (stronger isolation than containers).',
        'risk_tier': 'medium',
        'tags': ['sandbox', 'execution'],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 1,
            'financial': 0,
            'time': 2,
            'reversibility': 'reversible',
        },
        'typical_controls': ['ctrl.sandbox.resource-limits-strict', 'ctrl.sandbox.no-egress-default-deny'],
        'idempotency': 'partial',
        'determinism': 'captured',
    },
    {
        'id': 'ctrl.sandbox.no-egress-default-deny',
        'type': 'control',
        'pack_id': 'pack.01',
        'name': 'No Egress Default Deny',
        'description': 'Disable all outbound network by default; egress requires explicit allowlist.',
        'tags': ['sandbox', 'network', 'safety'],
        'enforcement_point': 'platform',
        'required_for_risk_tiers': ['medium', 'high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.sandbox.readonly-rootfs',
        'type': 'control',
        'pack_id': 'pack.01',
        'name': 'Read-Only Root Filesystem',
        'description': 'Root filesystem is read-only; only workspace mount is writable.',
        'tags': ['sandbox', 'filesystem'],
        'enforcement_point': 'platform',
        'required_for_risk_tiers': ['medium', 'high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.sandbox.workspace-mounts-only',
        'type': 'control',
        'pack_id': 'pack.01',
        'name': 'Workspace Mounts Only',
        'description': 'Only workspace path may be mounted; all other mounts denied.',
        'tags': ['sandbox', 'filesystem'],
        'enforcement_point': 'platform',
        'required_for_risk_tiers': ['medium', 'high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.sandbox.resource-limits-strict',
        'type': 'control',
        'pack_id': 'pack.01',
        'name': 'Strict Resource Limits',
        'description': 'Enforce CPU, RAM, and time limits on worker execution.',
        'tags': ['sandbox', 'reliability'],
        'enforcement_point': 'platform',
        'required_for_risk_tiers': ['low', 'medium', 'high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.sandbox.syscall-filtering',
        'type': 'control',
        'pack_id': 'pack.01',
        'name': 'Syscall Filtering',
        'description': 'Apply seccomp/AppArmor profiles to restrict permitted system calls.',
        'tags': ['sandbox', 'security'],
        'enforcement_point': 'platform',
        'required_for_risk_tiers': ['high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.sandbox.no-privileged-containers',
        'type': 'control',
        'pack_id': 'pack.01',
        'name': 'No Privileged Containers',
        'description': 'Container execution must not use privileged mode.',
        'tags': ['sandbox', 'security'],
        'enforcement_point': 'platform',
        'required_for_risk_tiers': ['low', 'medium', 'high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.sandbox.secrets-denied-by-default',
        'type': 'control',
        'pack_id': 'pack.01',
        'name': 'Secrets Denied by Default',
        'description': 'No secrets injected into workers unless explicitly granted.',
        'tags': ['sandbox', 'secrets', 'safety'],
        'enforcement_point': 'platform',
        'required_for_risk_tiers': ['low', 'medium', 'high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.sandbox.flight-recorder',
        'type': 'control',
        'pack_id': 'pack.01',
        'name': 'Flight Recorder',
        'description': 'Record all tool calls and file activity for audit purposes.',
        'tags': ['sandbox', 'observability', 'audit'],
        'enforcement_point': 'worker',
        'required_for_risk_tiers': ['medium', 'high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'ctrl.sandbox.path-allowlists',
        'type': 'control',
        'pack_id': 'pack.01',
        'name': 'Path Allowlists',
        'description': 'Deny access to sensitive filesystem paths not in the allowlist.',
        'tags': ['sandbox', 'filesystem', 'security'],
        'enforcement_point': 'platform',
        'required_for_risk_tiers': ['medium', 'high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.sandbox.no-egress',
        'type': 'profile',
        'pack_id': 'pack.01',
        'name': 'No-Egress Sandbox Profile',
        'description': 'No-egress sandbox posture: all outbound network disabled, workspace-only writes.',
        'tags': ['sandbox', 'network'],
        'controls_required': ['ctrl.sandbox.no-egress-default-deny', 'ctrl.sandbox.workspace-mounts-only', 'ctrl.sandbox.readonly-rootfs', 'ctrl.sandbox.secrets-denied-by-default'],
        'recommended_for_risk_tiers': ['medium', 'high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.sandbox.vm-strict',
        'type': 'profile',
        'pack_id': 'pack.01',
        'name': 'VM-Strict Sandbox Profile',
        'description': 'VM-isolated strict sandbox posture: full VM isolation, no privileged access.',
        'tags': ['sandbox', 'security'],
        'controls_required': ['ctrl.sandbox.no-egress-default-deny', 'ctrl.sandbox.resource-limits-strict', 'ctrl.sandbox.secrets-denied-by-default', 'ctrl.sandbox.flight-recorder'],
        'recommended_for_risk_tiers': ['high', 'critical'],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.sandbox.allowlisted-egress',
        'type': 'profile',
        'pack_id': 'pack.01',
        'name': 'Allowlisted Egress Sandbox Profile',
        'description': 'Sandbox posture allowing egress only to explicitly allowlisted destinations.',
        'tags': ['sandbox', 'network', 'egress'],
        'controls_required': ['ctrl.sandbox.path-allowlists', 'ctrl.sandbox.workspace-mounts-only', 'ctrl.sandbox.no-privileged-containers', 'ctrl.sandbox.flight-recorder'],
        'recommended_for_risk_tiers': ['medium', 'high'],
        'wcp_namespace': 'reserved',
    },
]
