"""Pack 04: DLQ / Repair / Replay Doctrine"""

PACKS = [
    {
        "id": "pack.04",
        "name": "DLQ / Repair / Replay Doctrine",
        "entity_count": 8,
    },
]

ENTITIES = [
    # --- Capabilities ---
    {
        "id": "cap.dlq.inspect",
        "type": "capability",
        "pack_id": "pack.04",
        "name": "Inspect Dead Letter Queue",
        "description": "Read and classify messages in the dead letter queue for triage.",
        "risk_tier": "low",
        "tags": ["dlq", "inspection", "repair"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.dlq.replay",
        "type": "capability",
        "pack_id": "pack.04",
        "name": "Replay DLQ Message",
        "description": "Re-enqueue a dead letter message for re-processing with replay controls.",
        "risk_tier": "medium",
        "tags": ["dlq", "replay", "repair"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 2, "network": 1, "financial": 1, "time": 1, "reversibility": "partially-reversible"},
        "typical_controls": ["ctrl.dlq.max_replay_attempts", "ctrl.obs.structured_logging"],
        "idempotency": "partial",
        "determinism": "captured",
    },
    {
        "id": "cap.dlq.purge",
        "type": "capability",
        "pack_id": "pack.04",
        "name": "Purge Dead Letter Queue",
        "description": "Permanently discard messages from the dead letter queue after review.",
        "risk_tier": "medium",
        "tags": ["dlq", "purge", "maintenance"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 2, "network": 0, "financial": 0, "time": 0, "reversibility": "irreversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only", "ctrl.dlq.max_replay_attempts"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.repair.reconcile_state",
        "type": "capability",
        "pack_id": "pack.04",
        "name": "Reconcile Broken State",
        "description": "Detect and repair inconsistent state by comparing source-of-truth with derived state.",
        "risk_tier": "high",
        "tags": ["repair", "reconcile", "consistency"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 3, "network": 1, "financial": 1, "time": 2, "reversibility": "partially-reversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only", "ctrl.obs.structured_logging"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.repair.compensate_transaction",
        "type": "capability",
        "pack_id": "pack.04",
        "name": "Execute Compensating Transaction",
        "description": "Execute a compensating transaction to undo a previously committed action.",
        "risk_tier": "high",
        "tags": ["repair", "saga", "compensation"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 3, "network": 2, "financial": 2, "time": 2, "reversibility": "partially-reversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only", "ctrl.obs.tracing_distributed"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    # --- Workers ---
    {
        "id": "wrk.dlq.janitor",
        "type": "worker",
        "pack_id": "pack.04",
        "name": "DLQ Janitor Worker",
        "description": "Periodic worker that inspects, classifies, and routes DLQ messages — retry, escalate, or purge.",
        "risk_tier": "medium",
        "tags": ["dlq", "janitor", "maintenance"],
        "wcp_namespace": "reserved",
        "serves_capabilities": ["cap.dlq.inspect", "cap.dlq.replay", "cap.dlq.purge"],
        "blast_radius_hint": {"data": 2, "network": 1, "financial": 1, "time": 1, "reversibility": "partially-reversible"},
        "required_controls": ["ctrl.obs.structured_logging", "ctrl.dlq.max_replay_attempts"],
        "idempotency": "partial",
        "determinism": "deterministic",
    },
    {
        "id": "wrk.repair.state_reconciler",
        "type": "worker",
        "pack_id": "pack.04",
        "name": "State Reconciler Worker",
        "description": "Scans entity state periodically, detects drift from authoritative source, and triggers repair.",
        "risk_tier": "medium",
        "tags": ["repair", "reconcile", "drift"],
        "wcp_namespace": "reserved",
        "serves_capabilities": ["cap.repair.reconcile_state"],
        "blast_radius_hint": {"data": 2, "network": 1, "financial": 0, "time": 2, "reversibility": "partially-reversible"},
        "required_controls": ["ctrl.obs.structured_logging", "ctrl.obs.audit_log_append_only"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    # --- Controls ---
    {
        "id": "ctrl.dlq.max_replay_attempts",
        "type": "control",
        "pack_id": "pack.04",
        "name": "Max Replay Attempts",
        "description": "Policy control: maximum number of times a DLQ message may be replayed before permanent discard.",
        "risk_tier": "low",
        "tags": ["dlq", "policy", "control"],
        "wcp_namespace": "reserved",
        "enforcement_point": "worker",
        "required_for_risk_tiers": ["low", "medium", "high", "critical"],
    },
]
