"""Pack 03: Observability & Flight Recorder"""

PACKS = [
    {
        "id": "pack.03",
        "name": "Observability & Flight Recorder",
        "entity_count": 11,
    },
]

ENTITIES = [
    # --- Capabilities ---
    {
        "id": "cap.side_effect.write_external",
        "type": "capability",
        "pack_id": "pack.03",
        "name": "Write External Side Effect",
        "description": "Perform a write to an external system (database, API, filesystem) as a declared side effect.",
        "risk_tier": "high",
        "tags": ["side-effects", "observability", "audit"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 3, "network": 2, "financial": 1, "time": 2, "reversibility": "partially-reversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only", "ctrl.obs.structured_logging"],
        "idempotency": "partial",
        "determinism": "captured",
    },
    {
        "id": "cap.ledger.write",
        "type": "capability",
        "pack_id": "pack.03",
        "name": "Write Audit Ledger",
        "description": "Append an immutable entry to the audit ledger.",
        "risk_tier": "high",
        "tags": ["audit", "ledger", "integrity"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 0, "financial": 0, "time": 0, "reversibility": "irreversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only"],
        "idempotency": "partial",
        "determinism": "deterministic",
    },
    {
        "id": "cap.outbox.publish",
        "type": "capability",
        "pack_id": "pack.03",
        "name": "Publish via Outbox",
        "description": "Publish a message via transactional outbox pattern ensuring at-least-once delivery.",
        "risk_tier": "medium",
        "tags": ["outbox", "messaging", "reliability"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 2, "financial": 0, "time": 1, "reversibility": "partially-reversible"},
        "typical_controls": ["ctrl.obs.structured_logging", "ctrl.obs.run_metadata_store"],
        "idempotency": "partial",
        "determinism": "captured",
    },
    {
        "id": "cap.inbox.dedup",
        "type": "capability",
        "pack_id": "pack.03",
        "name": "Inbox Deduplication",
        "description": "Deduplicate incoming messages using idempotency keys before processing.",
        "risk_tier": "low",
        "tags": ["inbox", "dedup", "reliability"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    # --- Controls ---
    {
        "id": "ctrl.obs.structured_logging",
        "type": "control",
        "pack_id": "pack.03",
        "name": "Structured Logging",
        "description": "All worker output must use structured (JSON) logging with correlation_id and tenant_id.",
        "tags": ["observability", "logging"],
        "enforcement_point": "worker",
        "required_for_risk_tiers": ["low", "medium", "high", "critical"],
    },
    {
        "id": "ctrl.obs.metrics_core",
        "type": "control",
        "pack_id": "pack.03",
        "name": "Core Metrics",
        "description": "Workers must emit core metrics (latency, error rate, throughput).",
        "tags": ["observability", "metrics"],
        "enforcement_point": "worker",
        "required_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "ctrl.obs.tracing_distributed",
        "type": "control",
        "pack_id": "pack.03",
        "name": "Distributed Tracing",
        "description": "Workers must emit distributed trace spans with correlation_id propagation.",
        "tags": ["observability", "tracing"],
        "enforcement_point": "worker",
        "required_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "ctrl.obs.audit_log_append_only",
        "type": "control",
        "pack_id": "pack.03",
        "name": "Append-Only Audit Log",
        "description": "Audit entries must be written to an append-only log; modifications forbidden.",
        "tags": ["observability", "audit", "integrity"],
        "enforcement_point": "platform",
        "required_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "ctrl.obs.run_metadata_store",
        "type": "control",
        "pack_id": "pack.03",
        "name": "Run Metadata Store",
        "description": "Store run metadata (inputs, outputs, timing, worker version) per execution.",
        "tags": ["observability", "provenance"],
        "enforcement_point": "worker",
        "required_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "ctrl.obs.slo_alerting",
        "type": "control",
        "pack_id": "pack.03",
        "name": "SLO Alerting",
        "description": "Alert when SLO thresholds are breached (error budget, latency p99).",
        "tags": ["observability", "slo", "reliability"],
        "enforcement_point": "platform",
        "required_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "ctrl.obs.flight_recorder_bundle",
        "type": "control",
        "pack_id": "pack.03",
        "name": "Flight Recorder Bundle",
        "description": "Collect and retain full flight recorder bundle (all events, tool calls, inputs/outputs) for forensic replay.",
        "tags": ["observability", "audit", "forensics"],
        "enforcement_point": "worker",
        "required_for_risk_tiers": ["high", "critical"],
    },
]
