"""Pack source — pack_24_ui_ux"""

ENTITIES = [
    {
        'id': 'cap.ui.review.queue',
        'type': 'capability',
        'name': 'Route to Review Queue',
        'description': 'Route a task or decision to a human review queue with explainability bundles.',
        'risk_tier': 'medium',
        'tags': [
            'ui',
            'human-in-loop',
            'review',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 0,
            'network': 0,
            'financial': 0,
            'time': 1,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
        ],
        'idempotency': 'partial',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.ui.form.collect',
        'type': 'capability',
        'name': 'Collect Form Input',
        'description': 'Present a structured form to a human user and collect validated input.',
        'risk_tier': 'low',
        'tags': [
            'ui',
            'forms',
            'human-in-loop',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 0,
            'network': 0,
            'financial': 0,
            'time': 1,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
        ],
        'idempotency': 'partial',
        'determinism': 'non-deterministic',
    },
    {
        'id': 'cap.ui.show-diff',
        'type': 'capability',
        'name': 'Show Diff for Review',
        'description': 'Display a structured diff of proposed changes to a human reviewer.',
        'risk_tier': 'low',
        'tags': [
            'ui',
            'diff',
            'review',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 0,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'typical_controls': [],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'cap.ui.capture-feedback',
        'type': 'capability',
        'name': 'Capture Human Feedback',
        'description': 'Collect structured feedback (thumbs, ratings, corrections) from a human user.',
        'risk_tier': 'low',
        'tags': [
            'ui',
            'feedback',
            'rlhf',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 0,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
        ],
        'idempotency': 'partial',
        'determinism': 'non-deterministic',
    },
    {
        'id': 'cap.ui.escalate-to-human',
        'type': 'capability',
        'name': 'Escalate to Human',
        'description': 'Interrupt automated processing and escalate to a human operator with full context.',
        'risk_tier': 'medium',
        'tags': [
            'ui',
            'escalation',
            'human-in-loop',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 0,
            'network': 0,
            'financial': 1,
            'time': 2,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.obs.audit-log-append-only',
            'ctrl.obs.structured-logging',
        ],
        'idempotency': 'partial',
        'determinism': 'non-deterministic',
    },
    {
        'id': 'wrk.ui.review-router',
        'type': 'worker_species',
        'name': 'Review Router Worker',
        'description': 'Route tasks to review queues with explainability bundles and SLAs.',
        'risk_tier': 'medium',
        'determinism': 'deterministic',
        'required_controls': [
            'ctrl.obs.structured-logging',
        ],
        'tags': [
            'ui',
            'human-in-loop',
        ],
        'serves_capabilities': [
            'cap.ui.review.queue',
            'cap.ui.escalate-to-human',
        ],
        'blast_radius_hint': {
            'data': 0,
            'network': 0,
            'financial': 0,
            'time': 1,
            'reversibility': 'reversible',
        },
        'idempotency': 'partial',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'wrk.ui.feedback-collector',
        'type': 'worker_species',
        'name': 'Feedback Collector Worker',
        'description': 'Collect structured human feedback tied to outcomes.',
        'risk_tier': 'low',
        'determinism': 'nondeterministic',
        'required_controls': [
            'ctrl.obs.structured-logging',
        ],
        'tags': [
            'ui',
            'feedback',
        ],
        'serves_capabilities': [
            'cap.ui.capture-feedback',
            'cap.ui.form.collect',
        ],
        'blast_radius_hint': {
            'data': 0,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'idempotency': 'partial',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.ui.review-strict',
        'type': 'profile',
        'name': 'Strict Review Queue UI Profile',
        'description': 'Strict review queue posture: mandatory human review for all high-stakes decisions, SLA tracking.',
        'tags': [
            'ui',
            'review',
            'compliance',
        ],
        'controls_required': [
            'ctrl.obs.audit-log-append-only',
            'ctrl.obs.structured-logging',
        ],
        'recommended_for_risk_tiers': [
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
]
