"""Pack 25: Edge/IoT & On-Prem Agents"""

PACKS = [
    {
        "id": "pack.25",
        "name": "Edge/IoT & On-Prem Agents",
        "entity_count": 10,
    },
]

ENTITIES = [
    # --- Capabilities ---
    {
        "id": "cap.edge.local_store",
        "type": "capability",
        "pack_id": "pack.25",
        "name": "Edge Local Store",
        "description": "Write data to local edge storage with TTL, size limits, and sync markers.",
        "risk_tier": "medium",
        "tags": ["edge", "storage", "offline"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 2, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.sandbox.resource_limits_strict", "ctrl.obs.structured_logging"],
        "idempotency": "partial",
        "determinism": "deterministic",
    },
    {
        "id": "cap.edge.sync",
        "type": "capability",
        "pack_id": "pack.25",
        "name": "Edge Sync",
        "description": "Sync local edge events and artifacts to cloud with conflict resolution.",
        "risk_tier": "medium",
        "tags": ["edge", "sync", "cloud"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 2, "network": 3, "financial": 1, "time": 2, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging", "ctrl.obs.tracing_distributed"],
        "idempotency": "partial",
        "determinism": "captured",
    },
    {
        "id": "cap.edge.device_attest",
        "type": "capability",
        "pack_id": "pack.25",
        "name": "Device Attestation",
        "description": "Attest the integrity and identity of an edge device using TPM or hardware root of trust.",
        "risk_tier": "high",
        "tags": ["edge", "security", "attestation"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 1, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.edge.update_agent",
        "type": "capability",
        "pack_id": "pack.25",
        "name": "Update Edge Agent",
        "description": "Apply a signed software update to an edge agent in a ring-based rollout.",
        "risk_tier": "critical",
        "tags": ["edge", "updates", "supply-chain"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 2, "financial": 1, "time": 3, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only", "ctrl.sandbox.resource_limits_strict"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.edge.local_inference",
        "type": "capability",
        "pack_id": "pack.25",
        "name": "Edge Local Inference",
        "description": "Run ML inference locally on the edge device without cloud connectivity.",
        "risk_tier": "medium",
        "tags": ["edge", "ml", "inference"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 1, "time": 2, "reversibility": "reversible"},
        "typical_controls": ["ctrl.sandbox.resource_limits_strict"],
        "idempotency": "partial",
        "determinism": "non-deterministic",
    },
    # --- Worker Species ---
    {
        "id": "wrk.edge.sync.agent",
        "type": "worker_species",
        "pack_id": "pack.25",
        "name": "Edge Sync Agent Worker",
        "description": "Sync local events/artifacts to cloud with conflict resolution and bandwidth budgets.",
        "risk_tier": "medium",
        "level": "L5",
        "guarantee": "at-least-once",
        "determinism": "captured-deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.structured_logging",
        ],
        "handles_capabilities": [
            "cap.edge.sync",
            "cap.edge.local_store",
        ],
        "tags": ["edge", "sync"],
        "serves_capabilities": ["cap.edge.sync", "cap.edge.local_store"],
        "blast_radius_hint": {"data": 2, "network": 3, "financial": 1, "time": 2, "reversibility": "reversible"},
        "idempotency": "partial",
    },
    {
        "id": "wrk.edge.update.manager",
        "type": "worker_species",
        "pack_id": "pack.25",
        "name": "Edge Update Manager Worker",
        "description": "Apply signed updates in rings; verify integrity; rollback on failures.",
        "risk_tier": "critical",
        "level": "L5",
        "guarantee": "at-least-once",
        "determinism": "deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.audit_log_append_only",
        ],
        "handles_capabilities": ["cap.edge.update_agent"],
        "tags": ["edge", "updates", "supply-chain"],
        "serves_capabilities": ["cap.edge.update_agent"],
        "blast_radius_hint": {"data": 1, "network": 2, "financial": 1, "time": 3, "reversibility": "reversible"},
        "idempotency": "full",
    },
    {
        "id": "wrk.edge.local_inference.worker",
        "type": "worker_species",
        "pack_id": "pack.25",
        "name": "Edge Local Inference Worker",
        "description": "Run local inference under constrained compute with strict sandboxing.",
        "risk_tier": "medium",
        "level": "L4",
        "guarantee": "best-effort",
        "determinism": "nondeterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.sandbox.resource_limits_strict",
        ],
        "handles_capabilities": ["cap.edge.local_inference"],
        "tags": ["edge", "ml", "inference"],
        "serves_capabilities": ["cap.edge.local_inference"],
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 1, "time": 2, "reversibility": "reversible"},
        "idempotency": "partial",
    },
    # --- Profiles ---
    {
        "id": "prof.edge.offline_strict",
        "type": "profile",
        "pack_id": "pack.25",
        "name": "Strict Offline Edge Profile",
        "description": "Strict offline-capable edge posture: local store, device attestation, no cloud dependency.",
        "tags": ["edge", "offline", "security"],
        "controls_required": [
            "ctrl.sandbox.resource_limits_strict",
            "ctrl.obs.structured_logging",
        ],
        "recommended_for_risk_tiers": ["medium", "high"],
    },
    {
        "id": "prof.edge.update_rings",
        "type": "profile",
        "pack_id": "pack.25",
        "name": "Ring-Based Update Edge Profile",
        "description": "Ring-based update posture: signed updates, ring rollout, integrity verification, audit trail.",
        "tags": ["edge", "updates", "supply-chain"],
        "controls_required": [
            "ctrl.obs.audit_log_append_only",
            "ctrl.sandbox.resource_limits_strict",
        ],
        "recommended_for_risk_tiers": ["high", "critical"],
    },
]
