"""Pack 15: Formal Policy & Authorization"""

PACKS = [
    {
        "id": "pack.15",
        "name": "Formal Policy & Authorization",
        "entity_count": 9,
    },
]

ENTITIES = [
    # --- Capabilities ---
    {
        "id": "cap.policy.evaluate",
        "type": "capability",
        "pack_id": "pack.15",
        "name": "Evaluate Policy",
        "description": "Evaluate an action against loaded policy rules and return allow/deny with rationale.",
        "risk_tier": "high",
        "tags": ["policy", "authorization", "governance"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.pol.policy_engine_runtime", "ctrl.pol.default_deny", "ctrl.pol.audit_policy_decisions"],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.policy.update",
        "type": "capability",
        "pack_id": "pack.15",
        "name": "Update Policy",
        "description": "Publish a new versioned policy to the policy engine for enforcement.",
        "risk_tier": "high",
        "tags": ["policy", "governance", "change-control"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 1, "network": 1, "financial": 2, "time": 2, "reversibility": "reversible"},
        "typical_controls": ["ctrl.pol.policy_versioning", "ctrl.obs.audit_log_append_only"],
        "idempotency": "partial",
        "determinism": "deterministic",
    },
    {
        "id": "cap.policy.canary",
        "type": "capability",
        "pack_id": "pack.15",
        "name": "Canary Policy Rollout",
        "description": "Activate a new policy version for a canary percentage of traffic before full rollout.",
        "risk_tier": "high",
        "tags": ["policy", "canary", "governance"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 1, "financial": 2, "time": 2, "reversibility": "reversible"},
        "typical_controls": ["ctrl.pol.policy_versioning", "ctrl.obs.audit_log_append_only"],
        "idempotency": "partial",
        "determinism": "deterministic",
    },
    # --- Worker Species ---
    {
        "id": "wrk.pol.policy_gate",
        "type": "worker_species",
        "pack_id": "pack.15",
        "name": "Policy Gate Worker",
        "description": "Evaluate actions against policy; emit allow/deny decisions and audit trail.",
        "risk_tier": "high",
        "level": "L6",
        "guarantee": "exactly-once",
        "determinism": "deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.pol.policy_engine_runtime",
            "ctrl.pol.default_deny",
            "ctrl.pol.audit_policy_decisions",
            "ctrl.pol.policy_versioning",
        ],
        "handles_capabilities": ["cap.policy.evaluate"],
        "tags": ["policy", "authorization", "governance"],
        "serves_capabilities": ["cap.policy.evaluate"],
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 2, "time": 0, "reversibility": "reversible"},
        "idempotency": "full",
    },
    # --- Controls ---
    {
        "id": "ctrl.pol.policy_engine_runtime",
        "type": "control",
        "pack_id": "pack.15",
        "name": "Policy Engine Runtime",
        "description": "Policy engine must be running and reachable before any guarded action executes.",
        "tags": ["policy", "governance"],
        "enforcement_point": "platform",
        "required_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "ctrl.pol.default_deny",
        "type": "control",
        "pack_id": "pack.15",
        "name": "Default Deny",
        "description": "Deny any capability not explicitly allowed by policy.",
        "tags": ["policy", "safety"],
        "enforcement_point": "hall",
        "required_for_risk_tiers": ["high", "critical"],
    },
    {
        "id": "ctrl.pol.audit_policy_decisions",
        "type": "control",
        "pack_id": "pack.15",
        "name": "Audit Policy Decisions",
        "description": "Log every policy allow/deny decision to the append-only audit ledger.",
        "tags": ["policy", "audit", "observability"],
        "enforcement_point": "worker",
        "required_for_risk_tiers": ["medium", "high", "critical"],
    },
    {
        "id": "ctrl.pol.policy_versioning",
        "type": "control",
        "pack_id": "pack.15",
        "name": "Policy Versioning",
        "description": "Policies must be versioned artifacts; unversioned policies cannot be enforced.",
        "tags": ["policy", "governance"],
        "enforcement_point": "hall",
        "required_for_risk_tiers": ["medium", "high", "critical"],
    },
    # --- Profiles ---
    {
        "id": "prof.pol.default_deny_strict",
        "type": "profile",
        "pack_id": "pack.15",
        "name": "Strict Default Deny Policy Profile",
        "description": "Strict policy posture: default-deny everything, versioned policies, full audit trail.",
        "tags": ["policy", "strict", "governance"],
        "controls_required": [
            "ctrl.pol.policy_engine_runtime",
            "ctrl.pol.default_deny",
            "ctrl.pol.audit_policy_decisions",
            "ctrl.pol.policy_versioning",
        ],
        "recommended_for_risk_tiers": ["high", "critical"],
    },
]
