"""Pack 24: UI/UX Agents (Forms, Review Queues, Human Feedback)"""

PACKS = [
    {
        "id": "pack.24",
        "name": "UI/UX Agents (Forms, Review Queues, Human Feedback)",
        "entity_count": 8,
    },
]

ENTITIES = [
    # --- Capabilities ---
    {
        "id": "cap.ui.review.queue",
        "type": "capability",
        "pack_id": "pack.24",
        "name": "Route to Review Queue",
        "description": "Route a task or decision to a human review queue with explainability bundles.",
        "risk_tier": "medium",
        "tags": ["ui", "human-in-loop", "review"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging"],
        "idempotency": "partial",
        "determinism": "deterministic",
    },
    {
        "id": "cap.ui.form.collect",
        "type": "capability",
        "pack_id": "pack.24",
        "name": "Collect Form Input",
        "description": "Present a structured form to a human user and collect validated input.",
        "risk_tier": "low",
        "tags": ["ui", "forms", "human-in-loop"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 1, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging"],
        "idempotency": "partial",
        "determinism": "non-deterministic",
    },
    {
        "id": "cap.ui.show_diff",
        "type": "capability",
        "pack_id": "pack.24",
        "name": "Show Diff for Review",
        "description": "Display a structured diff of proposed changes to a human reviewer.",
        "risk_tier": "low",
        "tags": ["ui", "diff", "review"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": [],
        "idempotency": "full",
        "determinism": "deterministic",
    },
    {
        "id": "cap.ui.capture_feedback",
        "type": "capability",
        "pack_id": "pack.24",
        "name": "Capture Human Feedback",
        "description": "Collect structured feedback (thumbs, ratings, corrections) from a human user.",
        "risk_tier": "low",
        "tags": ["ui", "feedback", "rlhf"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.structured_logging"],
        "idempotency": "partial",
        "determinism": "non-deterministic",
    },
    {
        "id": "cap.ui.escalate_to_human",
        "type": "capability",
        "pack_id": "pack.24",
        "name": "Escalate to Human",
        "description": "Interrupt automated processing and escalate to a human operator with full context.",
        "risk_tier": "medium",
        "tags": ["ui", "escalation", "human-in-loop"],
        "wcp_namespace": "reserved",
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 1, "time": 2, "reversibility": "reversible"},
        "typical_controls": ["ctrl.obs.audit_log_append_only", "ctrl.obs.structured_logging"],
        "idempotency": "partial",
        "determinism": "non-deterministic",
    },
    # --- Worker Species ---
    {
        "id": "wrk.ui.review_router",
        "type": "worker_species",
        "pack_id": "pack.24",
        "name": "Review Router Worker",
        "description": "Route tasks to review queues with explainability bundles and SLAs.",
        "risk_tier": "medium",
        "level": "L4",
        "guarantee": "at-least-once",
        "determinism": "deterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.structured_logging",
        ],
        "handles_capabilities": [
            "cap.ui.review.queue",
            "cap.ui.escalate_to_human",
        ],
        "tags": ["ui", "human-in-loop"],
        "serves_capabilities": ["cap.ui.review.queue", "cap.ui.escalate_to_human"],
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 1, "reversibility": "reversible"},
        "idempotency": "partial",
    },
    {
        "id": "wrk.ui.feedback_collector",
        "type": "worker_species",
        "pack_id": "pack.24",
        "name": "Feedback Collector Worker",
        "description": "Collect structured human feedback tied to outcomes.",
        "risk_tier": "low",
        "level": "L4",
        "guarantee": "best-effort",
        "determinism": "nondeterministic",
        "blast_score": None,
        "required_controls": [
            "ctrl.obs.structured_logging",
        ],
        "handles_capabilities": [
            "cap.ui.capture_feedback",
            "cap.ui.form.collect",
        ],
        "tags": ["ui", "feedback"],
        "serves_capabilities": ["cap.ui.capture_feedback", "cap.ui.form.collect"],
        "blast_radius_hint": {"data": 0, "network": 0, "financial": 0, "time": 0, "reversibility": "reversible"},
        "idempotency": "partial",
    },
    # --- Profiles ---
    {
        "id": "prof.ui.review_strict",
        "type": "profile",
        "pack_id": "pack.24",
        "name": "Strict Review Queue UI Profile",
        "description": "Strict review queue posture: mandatory human review for all high-stakes decisions, SLA tracking.",
        "tags": ["ui", "review", "compliance"],
        "controls_required": [
            "ctrl.obs.audit_log_append_only",
            "ctrl.obs.structured_logging",
        ],
        "recommended_for_risk_tiers": ["high", "critical"],
    },
]
