"""Pack source — pack_11_notifications"""

ENTITIES = [
    {
        'id': 'cap.notify.send-email',
        'type': 'capability',
        'name': 'Send Email',
        'description': 'Send a transactional or notification email via configured email provider.',
        'risk_tier': 'medium',
        'tags': [
            'notifications',
            'email',
            'egress',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 2,
            'financial': 1,
            'time': 1,
            'reversibility': 'irreversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
            'ctrl.obs.metrics-core',
        ],
        'idempotency': 'partial',
        'determinism': 'captured',
    },
    {
        'id': 'cap.notify.send-sms',
        'type': 'capability',
        'name': 'Send SMS',
        'description': 'Send an SMS notification via configured telephony provider.',
        'risk_tier': 'medium',
        'tags': [
            'notifications',
            'sms',
            'egress',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 2,
            'financial': 2,
            'time': 1,
            'reversibility': 'irreversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
            'ctrl.obs.metrics-core',
        ],
        'idempotency': 'partial',
        'determinism': 'captured',
    },
    {
        'id': 'cap.notify.send-push',
        'type': 'capability',
        'name': 'Send Push Notification',
        'description': 'Send a push notification to a mobile/web device via push provider.',
        'risk_tier': 'low',
        'tags': [
            'notifications',
            'push',
            'egress',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 0,
            'network': 2,
            'financial': 0,
            'time': 1,
            'reversibility': 'irreversible',
        },
        'typical_controls': [
            'ctrl.obs.structured-logging',
        ],
        'idempotency': 'partial',
        'determinism': 'captured',
    },
    {
        'id': 'cap.notify.manage-suppression',
        'type': 'capability',
        'name': 'Manage Suppression Lists',
        'description': 'Add, remove, or query suppression list entries (unsubscribes, bounces, complaints).',
        'risk_tier': 'medium',
        'tags': [
            'notifications',
            'suppression',
            'compliance',
        ],
        'wcp_namespace': 'reserved',
        'blast_radius_hint': {
            'data': 1,
            'network': 0,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'typical_controls': [
            'ctrl.obs.audit-log-append-only',
            'ctrl.obs.structured-logging',
        ],
        'idempotency': 'full',
        'determinism': 'deterministic',
    },
    {
        'id': 'wrk.notify.delivery.worker',
        'type': 'worker_species',
        'name': 'Notification Delivery Worker',
        'description': 'Send email/SMS/push with deliverability controls and idempotency.',
        'risk_tier': 'medium',
        'determinism': 'captured-deterministic',
        'required_controls': [
            'ctrl.obs.structured-logging',
            'ctrl.obs.metrics-core',
        ],
        'tags': [
            'notifications',
            'egress',
        ],
        'serves_capabilities': [
            'cap.notify.send-email',
            'cap.notify.send-sms',
            'cap.notify.send-push',
        ],
        'blast_radius_hint': {
            'data': 1,
            'network': 2,
            'financial': 2,
            'time': 1,
            'reversibility': 'irreversible',
        },
        'idempotency': 'partial',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'wrk.notify.webhook.ingest',
        'type': 'worker_species',
        'name': 'Notification Webhook Ingest Worker',
        'description': 'Ingest provider webhooks (bounces/complaints), update suppression.',
        'risk_tier': 'medium',
        'determinism': 'deterministic',
        'required_controls': [
            'ctrl.obs.structured-logging',
        ],
        'tags': [
            'notifications',
            'webhooks',
        ],
        'serves_capabilities': [
            'cap.notify.manage-suppression',
        ],
        'blast_radius_hint': {
            'data': 1,
            'network': 1,
            'financial': 0,
            'time': 0,
            'reversibility': 'reversible',
        },
        'idempotency': 'full',
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.notify.standard',
        'type': 'profile',
        'name': 'Standard Notification Profile',
        'description': 'Standard notification posture with deliverability logging and suppression checks.',
        'tags': [
            'notifications',
            'standard',
        ],
        'controls_required': [
            'ctrl.obs.structured-logging',
            'ctrl.obs.metrics-core',
        ],
        'recommended_for_risk_tiers': [
            'low',
            'medium',
        ],
        'wcp_namespace': 'reserved',
    },
    {
        'id': 'prof.notify.compliance-strict',
        'type': 'profile',
        'name': 'Strict Compliance Notification Profile',
        'description': 'Strict notification posture for regulated channels: audit, suppression, and consent enforcement.',
        'tags': [
            'notifications',
            'compliance',
            'strict',
        ],
        'controls_required': [
            'ctrl.obs.audit-log-append-only',
            'ctrl.obs.structured-logging',
            'ctrl.obs.metrics-core',
        ],
        'recommended_for_risk_tiers': [
            'high',
            'critical',
        ],
        'wcp_namespace': 'reserved',
    },
]
